// Generated by ReScript, PLEASE EDIT WITH CARE

import Ava from "ava";
import * as Tilia from "../src/Tilia.mjs";
import * as Clouds from "./Clouds.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as React from "@testing-library/react";
import UserEvent from "@testing-library/user-event";

var Html = {};

var UserEvent$1 = {};

var Testing = {};

var user = UserEvent;

Ava("re-render on changes", (async function (t) {
        var tree = Tilia.use({
              flowers: "Are nice",
              clouds: {
                morning: "can be pink",
                evening: "can be dark"
              }
            });
        var onClick = function () {
          tree.clouds.evening = "Blue";
        };
        React.render(JsxRuntime.jsx(Clouds.make, {
                  tree: tree,
                  onClick: onClick
                }));
        await React.screen.findByRole("button");
        await user.click(React.screen.getByRole("button"));
        await React.screen.findByRole("clouds");
        console.log(React.screen.getByRole("clouds"));
      }));

export {
  Html ,
  UserEvent$1 as UserEvent,
  Testing ,
  user ,
}
/* user Not a pure module */
