// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let install = (function install(factory, keyRange) {
  globalThis.indexedDB = factory;
  globalThis.IDBKeyRange = keyRange;
});

let uninstall = (function uninstall() {
  delete globalThis.indexedDB;
  delete globalThis.IDBKeyRange;
});

let later = (function later(fn) {
  setTimeout(fn, 0);
});

function compare(a, b) {
  if (Array.isArray(a)) {
    if (Array.isArray(b)) {
      return compareAll(a, b);
    }
    switch (typeof b) {
      case "string" :
        return 1;
      default:
        return 0;
    }
  } else {
    switch (typeof a) {
      case "string" :
        if (Array.isArray(b)) {
          return -1;
        }
        switch (typeof b) {
          case "string" :
            if (a < b) {
              return -1;
            } else if (a > b) {
              return 1;
            } else {
              return 0;
            }
          default:
            return 0;
        }
      default:
        return 0;
    }
  }
}

function compareAll(a, b) {
  let result = 0;
  let index = 0;
  while (result === 0 && index < Math.min(a.length, b.length)) {
    result = compare(a[index], b[index]);
    index = index + 1 | 0;
  };
  if (result !== 0) {
    return result;
  } else {
    return a.length - b.length | 0;
  }
}

function asKey(key) {
  return key.map(part => (part));
}

function within(range, key) {
  if (compare(range.lower, asKey(key)) <= 0) {
    return compare(asKey(key), range.upper) <= 0;
  } else {
    return false;
  }
}

let keyRange = {
  bound: (lower, upper) => ({
    lower: lower,
    upper: upper
  })
};

function answering(produce) {
  let request = {
    onsuccess: () => {},
    onerror: () => {},
    onupgradeneeded: () => {},
    result: undefined,
    error: new Error("not failed")
  };
  later(() => {
    request.result = produce();
    request.onsuccess();
  });
  return request;
}

function make(failOpenOpt, param) {
  let failOpen = failOpenOpt !== undefined ? failOpenOpt : false;
  let control = {
    transactions: 0,
    failing: false
  };
  let rows = {};
  let id = key => Stdlib_Option.getOr(JSON.stringify(key), "");
  let sorted = () => Object.entries(rows).toSorted((param, param$1) => compare(JSON.parse(param[0]), JSON.parse(param$1[0]))).map(param => [
    JSON.parse(param[0]),
    param[1]
  ]);
  let matching = range => sorted().filter(param => {
    let key = param[0];
    if (Array.isArray(key)) {
      return within(range, Stdlib_Array.filterMap(key, part => {
        if (typeof part === "string") {
          return part;
        }
      }));
    } else {
      return false;
    }
  });
  let database_objectStoreNames = {
    contains: param => true
  };
  let database_createObjectStore = (param, param$1) => {};
  let database_transaction = (param, param$1) => {
    control.transactions = control.transactions + 1 | 0;
    let writes = [];
    let tx = {
      objectStore: param => ({
        get: key => answering(() => {
          let row = rows[id(key)];
          if (row !== undefined) {
            return row;
          } else {
            return null;
          }
        }),
        getAll: range => answering(() => matching(range).map(param => param[1])),
        getAllKeys: range => answering(() => matching(range).map(param => {
          let key = param[0];
          if (Array.isArray(key)) {
            return Stdlib_Array.filterMap(key, part => {
              if (typeof part === "string") {
                return part;
              }
            });
          } else {
            return [];
          }
        })),
        put: row => {
          writes.push(() => {
            rows[id([
                  row.tag,
                  row.key
                ])] = row;
          });
        },
        delete: key => {
          writes.push(() => Stdlib_Dict.$$delete(rows, id(key)));
        }
      }),
      onerror: () => {},
      onabort: () => {},
      error: new Error("transaction aborted")
    };
    later(() => {
      if (control.failing) {
        return tx.onabort();
      } else {
        writes.forEach(write => write());
        return;
      }
    });
    return tx;
  };
  let database = {
    objectStoreNames: database_objectStoreNames,
    createObjectStore: database_createObjectStore,
    transaction: database_transaction
  };
  let factory = {
    open: (param, param$1) => {
      let request = {
        onsuccess: () => {},
        onerror: () => {},
        onupgradeneeded: () => {},
        result: database,
        error: new Error("cannot open")
      };
      later(() => {
        if (failOpen) {
          return request.onerror();
        } else {
          request.onupgradeneeded();
          return request.onsuccess();
        }
      });
      return request;
    }
  };
  install(factory, keyRange);
  return control;
}

export {
  install,
  uninstall,
  later,
  compare,
  compareAll,
  asKey,
  within,
  keyRange,
  answering,
  make,
}
/* No side effect */
