// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Vitest$1 from "@epure/vitest";
import * as FakeIndexedDb from "./FakeIndexedDb.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as TiliaQueryIndexedDb from "../src/TiliaQueryIndexedDb.mjs";

Vitest$1.Given("a keyspace", param => {
  let step = param.step;
  let control = {
    contents: undefined
  };
  let errors = {
    contents: []
  };
  let build = (failOpenOpt, presentOpt, param) => {
    let failOpen = failOpenOpt !== undefined ? failOpenOpt : false;
    let present = presentOpt !== undefined ? presentOpt : true;
    if (present) {
      control.contents = FakeIndexedDb.make(failOpen, undefined);
    } else {
      control.contents = undefined;
      FakeIndexedDb.uninstall();
    }
    return TiliaQueryIndexedDb.make({
      name: "cards",
      onError: error => {
        errors.contents = errors.contents.concat([error]);
      }
    });
  };
  let kv = {
    contents: build(undefined, undefined, undefined)
  };
  let settled = () => new Promise((resolve, param) => {
    setTimeout(() => resolve(), 0);
  });
  let read = (tag, keys) => new Promise((resolve, param) => kv.contents.get(tag, keys, values => resolve(values)));
  let list = tag => new Promise((resolve, param) => kv.contents.keys(tag, keys => resolve(keys)));
  step("the database cannot open", () => {
    kv.contents = build(true, undefined, undefined);
  });
  step("there is no IndexedDB at all", () => {
    kv.contents = build(undefined, false, undefined);
  });
  step("the database has opened", () => settled());
  step("time passes", () => settled());
  step("I write under {string}", (tag, table) => {
    Vitest$1.toRecords(table).forEach(entry => kv.contents.set(tag, entry.key, entry.value));
  });
  step("I write {number} rows under {string}", (count, tag) => {
    Stdlib_Array.make(count | 0, 0).forEach((param, index) => kv.contents.set(tag, `id-` + index.toString(), index.toString()));
  });
  step("I delete {string} under {string}", (key, tag) => kv.contents.set(tag, key, undefined));
  step("transactions are counted from now", () => {
    Stdlib_Option.getOrThrow(control.contents, "no fake database").transactions = 0;
  });
  step("every transaction aborts", () => {
    Stdlib_Option.getOrThrow(control.contents, "no fake database").failing = true;
  });
  step("transactions succeed again", () => {
    Stdlib_Option.getOrThrow(control.contents, "no fake database").failing = false;
  });
  step("{number} transaction(s) should have been used", count => Vitest.expect(Stdlib_Option.getOrThrow(control.contents, "no fake database").transactions).toBe(count | 0));
  let expectValues = (values, table) => Vitest.expect(values).toEqual(Vitest$1.toRecords(table).map(entry => entry.value));
  step("reading {string} should answer", (tag, table) => read(tag, undefined).then(values => expectValues(values, table)));
  step("reading {string} for {string} should answer", (tag, keys, table) => read(tag, keys.split(", ")).then(values => expectValues(values, table)));
  step("writing {string} under {string} and reading it back at once should answer {string}", (key, tag, expected) => {
    kv.contents.set(tag, key, expected);
    return read(tag, [key]).then(values => Vitest.expect(values).toEqual([expected]));
  });
  step("reading {string} should answer nothing", tag => read(tag, undefined).then(values => Vitest.expect(values).toEqual([])));
  step("listing {string} should answer", (tag, table) => list(tag).then(keys => Vitest.expect(keys).toEqual(Vitest$1.toRecords(table).map(entry => entry.key))));
  step("listing {string} should answer nothing", tag => list(tag).then(keys => Vitest.expect(keys).toEqual([])));
  step("listing {string} should have {number} keys", (tag, count) => list(tag).then(keys => Vitest.expect(keys.length).toBe(count | 0)));
  let early = {
    contents: undefined
  };
  step("I read {string} without waiting for the database", tag => {
    early.contents = read(tag, undefined);
  });
  step("the read should have answered", table => Stdlib_Option.getOrThrow(early.contents, "no early read").then(values => expectValues(values, table)));
  step("an error should have been reported", () => Vitest.expect(errors.contents.length !== 0).toBe(true));
});

/*  Not a pure module */
