// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TiliaQuery from "../src/TiliaQuery.mjs";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function make() {
  let queue = [];
  return {
    respond: f => {
      queue.push(f);
    },
    flush: () => {
      queue.forEach(f => f());
      queue.splice(0, queue.length);
    }
  };
}

let Network = {
  make: make
};

function id(card) {
  return card.id;
}

function matches(query, card) {
  return card.deck === query.deck;
}

function sort(a, b) {
  if (a.id < b.id) {
    return -1.0;
  } else if (a.id > b.id) {
    return 1.0;
  } else {
    return 0.0;
  }
}

function make$1(network) {
  let data = {};
  let respond = value => new Promise((resolve, param) => network.respond(() => resolve(value)));
  let upsert = card => {
    let actual = Stdlib_Option.getOr(Stdlib_Option.flatMap(data[card.id], c => c.version), 0.0);
    let incoming = Stdlib_Option.getOr(card.version, 0.0);
    if (incoming !== 0.0 && incoming !== actual) {
      return respond({
        TAG: "Error",
        _0: `version conflict on "` + card.id + `"`
      });
    }
    let newrecord = {...card};
    newrecord.version = actual + 1.0;
    data[card.id] = newrecord;
    return respond({
      TAG: "Ok",
      _0: newrecord
    });
  };
  let remove = id => {
    Stdlib_Dict.$$delete(data, id);
    return respond({
      TAG: "Ok",
      _0: undefined
    });
  };
  let _select = filter => Object.values(data).filter(filter);
  let select = filter => respond(Object.values(data).filter(filter));
  return {
    select: select,
    upsert: upsert,
    remove: remove,
    _select: _select
  };
}

let Papabase = {
  make: make$1
};

function makeTable(getKey) {
  let data = {};
  let get = async key => data[key];
  let put = async row => {
    data[getKey(row)] = row;
  };
  let $$delete = async key => Stdlib_Dict.$$delete(data, key);
  let _select = f => Object.values(data).filter(f);
  let filter = async f => Object.values(data).filter(f);
  return {
    get: get,
    put: put,
    delete: $$delete,
    filter: filter,
    _select: _select
  };
}

function make$2() {
  return {
    cards: makeTable(card => card.id),
    kv: makeTable(entry => entry.key)
  };
}

let Dexme = {
  makeTable: makeTable,
  make: make$2
};

function make$3(papabase, online_) {
  return {
    online: online_,
    fetch: (query, channel) => {
      papabase.select(card => matches(query, card)).then(channel.set);
    },
    push: (ops, channel) => {
      ops.forEach(op => {
        if (op.op === "upsert") {
          papabase.upsert(op.value).then(result => {
            if (result.TAG === "Ok") {
              return channel.set(result._0);
            } else {
              return channel.fail(result._0);
            }
          });
          return;
        }
        let id = op.id;
        papabase.remove(id).then(result => {
          if (result.TAG === "Ok") {
            return channel.removed(id);
          } else {
            return channel.fail(result._0);
          }
        });
      });
    }
  };
}

let PapabaseAdaptor = {
  make: make$3
};

function kvKey(tag, key) {
  return tag + `/` + key;
}

function make$4(dexme) {
  return {
    fetch: (query, channel) => {
      dexme.cards.filter(card => matches(query, card)).then(result => channel.set(result));
    },
    push: ops => {
      ops.forEach(op => {
        if (op.op === "upsert") {
          dexme.cards.put(op.value);
          return;
        }
        dexme.cards.delete(op.id);
      });
    },
    set: (tag, key, value) => {
      if (value !== undefined) {
        dexme.kv.put({
          key: kvKey(tag, key),
          value: value
        });
      } else {
        dexme.kv.delete(kvKey(tag, key));
      }
    },
    get: (tag, key, set) => {
      if (key !== undefined) {
        dexme.kv.get(kvKey(tag, key)).then(result => set(Stdlib_Option.mapOr(result, [], e => [e.value])));
      } else {
        dexme.kv.filter(e => e.key.startsWith(tag + `/`)).then(result => set(result.map(e => e.value)));
      }
    }
  };
}

let DexmeAdaptor = {
  kvKey: kvKey,
  make: make$4
};

function sortByEnglish(a, b) {
  if (a.english < b.english) {
    return -1.0;
  } else if (a.english > b.english) {
    return 1.0;
  } else {
    return 0.0;
  }
}

function make$5(dexme, expiryOpt, papabase, now_, online_) {
  let expiry = expiryOpt !== undefined ? expiryOpt : ({
      refresh: 2.0,
      memory: 4.0,
      local: 8.0
    });
  let remote = make$3(papabase, online_);
  let now = () => now_.value;
  let sort = array => array.toSorted(sortByEnglish);
  if (dexme === undefined) {
    return TiliaQuery.make(id, matches, remote, undefined, expiry, now, undefined, sort);
  }
  let local = make$4(dexme);
  return TiliaQuery.make(id, matches, remote, local, expiry, now, undefined, sort);
}

export {
  Network,
  id,
  matches,
  sort,
  Papabase,
  Dexme,
  PapabaseAdaptor,
  DexmeAdaptor,
  sortByEnglish,
  make$5 as make,
}
/* TiliaQuery Not a pure module */
