// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TiliaQuery from "../src/TiliaQuery.mjs";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function make() {
  let queue = [];
  return {
    respond: f => {
      queue.push(f);
    },
    flush: () => {
      queue.forEach(f => f());
      queue.splice(0, queue.length);
    }
  };
}

let Network = {
  make: make
};

function id(card) {
  return card.id;
}

function clone(card) {
  let newrecord = {...card};
  newrecord.id = card.id;
  return newrecord;
}

function matches(query, card) {
  if (card.deck === query.deck) {
    return Stdlib_Option.mapOr(query.seen, true, seen => card.seen === seen);
  } else {
    return false;
  }
}

function make$1(network) {
  let data = {};
  let respond = value => new Promise((resolve, param) => network.respond(() => resolve(value)));
  let upsert = card => {
    let actual = Stdlib_Option.getOr(Stdlib_Option.flatMap(data[card.id], c => c.version), 0.0);
    let incoming = Stdlib_Option.getOr(card.version, 0.0);
    if (incoming !== 0.0 && incoming !== actual) {
      return respond({
        TAG: "Error",
        _0: `version conflict on "` + card.id + `"`
      });
    }
    let newrecord = {...card};
    newrecord.version = actual + 1.0;
    data[card.id] = newrecord;
    return respond({
      TAG: "Ok",
      _0: newrecord
    });
  };
  let _put = card => {
    data[card.id] = card;
  };
  let remove = id => {
    Stdlib_Dict.$$delete(data, id);
    return respond({
      TAG: "Ok",
      _0: undefined
    });
  };
  let failing = {
    contents: undefined
  };
  let _select = filter => Object.values(data).filter(filter).map(clone);
  let select = filter => {
    let message = failing.contents;
    if (message !== undefined) {
      return respond({
        TAG: "Error",
        _0: message
      });
    } else {
      return respond({
        TAG: "Ok",
        _0: _select(filter)
      });
    }
  };
  return {
    select: select,
    upsert: upsert,
    remove: remove,
    _select: _select,
    _put: _put,
    _failing: message => {
      failing.contents = message;
    },
    _network: network
  };
}

let Papabase = {
  make: make$1
};

function makeTable(getKey) {
  let data = {};
  let get = async key => data[key];
  let put = async row => {
    data[getKey(row)] = row;
  };
  let $$delete = async key => Stdlib_Dict.$$delete(data, key);
  let _select = f => Object.values(data).filter(f);
  let filter = async f => Object.values(data).filter(f);
  return {
    get: get,
    put: put,
    delete: $$delete,
    filter: filter,
    _select: _select
  };
}

function make$2() {
  return {
    cards: makeTable(card => card.id),
    kv: makeTable(entry => entry.key),
    partial: false
  };
}

let Dexme = {
  makeTable: makeTable,
  make: make$2
};

function make$3(papabase, online_) {
  return {
    online: online_,
    fetch: (query, channel) => {
      papabase.select(card => matches(query, card)).then(result => {
        if (result.TAG === "Ok") {
          return channel.fresh(result._0);
        } else {
          return channel.fail(result._0);
        }
      });
    },
    push: (ops, channel) => {
      ops.forEach(op => {
        if (op.op === "upsert") {
          papabase.upsert(op.value).then(result => {
            if (result.TAG === "Ok") {
              return channel.set(result._0);
            } else {
              return channel.fail(result._0);
            }
          });
          return;
        }
        let id = op.id;
        papabase.remove(id).then(result => {
          if (result.TAG === "Ok") {
            return channel.removed(id);
          } else {
            return channel.fail(result._0);
          }
        });
      });
    }
  };
}

let PapabaseAdaptor = {
  make: make$3
};

function kvKey(tag, key) {
  return tag + `/` + key;
}

function make$4(dexme) {
  return {
    fetch: (query, channel) => {
      dexme.cards.filter(card => matches(query, card)).then(result => {
        if (dexme.partial || result.length === 0) {
          return channel.partial(result);
        } else {
          return channel.local(result);
        }
      });
    },
    push: ops => {
      ops.forEach(op => {
        if (op.op === "upsert") {
          dexme.cards.put(op.value);
          return;
        }
        dexme.cards.delete(op.id);
      });
    },
    set: (tag, key, value) => {
      if (value !== undefined) {
        dexme.kv.put({
          key: kvKey(tag, key),
          value: value
        });
      } else {
        dexme.kv.delete(kvKey(tag, key));
      }
    },
    get: (tag, key, set) => {
      if (key !== undefined) {
        dexme.kv.get(kvKey(tag, key)).then(result => set(Stdlib_Option.mapOr(result, [], e => [e.value])));
      } else {
        dexme.kv.filter(e => e.key.startsWith(tag + `/`)).then(result => set(result.map(e => e.value)));
      }
    },
    ids: set => {
      dexme.cards.filter(param => true).then(cards => set(cards.map(card => card.id)));
    }
  };
}

let DexmeAdaptor = {
  kvKey: kvKey,
  make: make$4
};

function make$5() {
  return {
    rejects: {},
    conflicts: {},
    transientFrom: undefined,
    failAfter: undefined
  };
}

function opId(op) {
  if (op.op === "upsert") {
    return op.value.id;
  } else {
    return op.id;
  }
}

function wrap(rules, network, remote) {
  let later = f => {
    new Promise((resolve, param) => network.respond(() => resolve())).then(f);
  };
  return {
    online: remote.online,
    fetch: remote.fetch,
    push: (ops, channel) => {
      let ended = {
        contents: false
      };
      ops.forEach(op => {
        if (ended.contents) {
          return;
        }
        let oid = opId(op);
        let from = rules.transientFrom;
        let exit = 0;
        if (from !== undefined && from === oid) {
          ended.contents = true;
          later(() => channel.retry());
        } else {
          exit = 1;
        }
        if (exit === 1) {
          let message = rules.rejects[oid];
          if (message !== undefined) {
            later(() => channel.reject(oid, message));
          } else {
            let row = rules.conflicts[oid];
            if (row !== undefined) {
              Stdlib_Dict.$$delete(rules.conflicts, oid);
              later(() => channel.conflict(row));
            } else {
              remote.push([op], channel);
            }
          }
        }
        let match = rules.failAfter;
        if (match === undefined) {
          return;
        }
        if (match[0] !== oid) {
          return;
        }
        let message$1 = match[1];
        ended.contents = true;
        later(() => channel.fail(message$1));
      });
    }
  };
}

let Rules = {
  make: make$5,
  opId: opId,
  wrap: wrap
};

function make$6(network) {
  return {
    network: network,
    enabled: false,
    endsInFetch: false,
    channel: undefined,
    superseded: undefined,
    cleanups: 0,
    fetches: 0
  };
}

function wrap$1(live, papabase, remote) {
  return {
    online: remote.online,
    fetch: (query, channel) => {
      live.fetches = live.fetches + 1 | 0;
      live.superseded = live.channel;
      live.channel = channel;
      if (live.endsInFetch) {
        channel.end();
        return channel.finally(() => {
          live.cleanups = live.cleanups + 1 | 0;
        });
      } else if (live.enabled) {
        channel.finally(() => {
          live.cleanups = live.cleanups + 1 | 0;
        });
        return live.network.respond(() => channel.live(papabase._select(card => matches(query, card))));
      } else {
        return remote.fetch(query, channel);
      }
    },
    push: remote.push
  };
}

let Live = {
  make: make$6,
  wrap: wrap$1
};

function make$7() {
  return {
    accepted: true,
    calls: []
  };
}

function run(merge, change, remote) {
  let local;
  switch (change.change) {
    case "clean" :
      local = change.value;
      break;
    case "created" :
      local = change.edited;
      break;
    case "updated" :
      local = change.edited;
      break;
    case "removed" :
      local = change.base;
      break;
  }
  let snapshot;
  switch (change.change) {
    case "clean" :
      snapshot = {
        change: "clean",
        value: clone(change.value)
      };
      break;
    case "created" :
      snapshot = {
        change: "created",
        edited: clone(change.edited)
      };
      break;
    case "updated" :
      snapshot = {
        change: "updated",
        base: clone(change.base),
        edited: clone(change.edited)
      };
      break;
    case "removed" :
      snapshot = {
        change: "removed",
        base: clone(change.base)
      };
      break;
  }
  merge.calls.push({
    change: snapshot,
    remote: clone(remote)
  });
  if (merge.accepted) {
    local.deck = remote.deck;
    local.english = remote.english;
    local.translation = remote.translation;
    if (change.change === "clean") {
      local.seen = remote.seen;
    }
  }
  return merge.accepted;
}

let Merge = {
  make: make$7,
  run: run
};

function sortBySeen(a, b) {
  if (a.seen < b.seen) {
    return -1.0;
  } else if (a.seen > b.seen) {
    return 1.0;
  } else if (a.english < b.english) {
    return -1.0;
  } else if (a.english > b.english) {
    return 1.0;
  } else {
    return 0.0;
  }
}

function make$8() {
  return {
    unavailable: false,
    attempts: 0
  };
}

function wrap$2(push, remote) {
  return {
    online: remote.online,
    fetch: remote.fetch,
    push: (ops, channel) => {
      push.attempts = push.attempts + 1 | 0;
      if (push.unavailable) {
        return channel.retry();
      } else {
        return remote.push(ops, channel);
      }
    }
  };
}

let Push = {
  make: make$8,
  wrap: wrap$2
};

function make$9(dexme, live, push, rules, mergeOpt, onError, papabase, now, online_) {
  let merge = mergeOpt !== undefined ? mergeOpt : ({
      accepted: true,
      calls: []
    });
  let remote = make$3(papabase, online_);
  let remote$1 = live !== undefined ? wrap$1(live, papabase, remote) : remote;
  let remote$2 = rules !== undefined ? wrap(rules, papabase._network, remote$1) : remote$1;
  let remote$3 = push !== undefined ? wrap$2(push, remote$2) : remote$2;
  let sort = _query => (array => array.toSorted(sortBySeen));
  let mergeValues = (change, remote) => run(merge, change, remote);
  if (dexme === undefined) {
    return TiliaQuery.make({
      id: id,
      matches: matches,
      remote: remote$3,
      now: now,
      sort: sort,
      merge: mergeValues,
      onError: onError
    });
  }
  let local = make$4(dexme);
  return TiliaQuery.make({
    id: id,
    matches: matches,
    remote: remote$3,
    local: local,
    now: now,
    sort: sort,
    merge: mergeValues,
    onError: onError
  });
}

export {
  Network,
  id,
  clone,
  matches,
  Papabase,
  Dexme,
  PapabaseAdaptor,
  DexmeAdaptor,
  Rules,
  Live,
  Merge,
  sortBySeen,
  Push,
  make$9 as make,
}
/* TiliaQuery Not a pure module */
