// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Vitest from "vitest";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";
import * as TiliaQuery from "../src/TiliaQuery.mjs";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function item(id, name, count) {
  return {
    id: id,
    name: name,
    count: count
  };
}

function make(_table, id, remote, local, stale, gc, now, matches, sort) {
  return TiliaQuery.make({
    id: id,
    remote: remote,
    local: local,
    stale: stale,
    gc: gc,
    now: now,
    matches: matches,
    sort: sort
  });
}

let Papabase = {
  make: make
};

function fromItems(items) {
  let dict = {};
  items.forEach(item => {
    dict[item.id] = item;
  });
  return dict;
}

function get(dict, id) {
  let value = dict[id];
  if (value !== undefined) {
    return Primitive_option.valFromOption(value);
  } else {
    return Pervasives.failwith("Expected task in store");
  }
}

function byStatus(dict, status) {
  return Object.entries(dict).map(param => param[1]).filter(item => item.name === status);
}

let Store = {
  fromItems: fromItems,
  get: get,
  byStatus: byStatus
};

let Runtime = {};

function pushOutcome(remote, id, outcome) {
  let values = remote.outcomes.contents[id];
  if (values !== undefined) {
    remote.outcomes.contents[id] = Belt_Array.concatMany([
      values,
      [outcome]
    ]);
  } else {
    remote.outcomes.contents[id] = [outcome];
  }
}

function takeHeld(remote, index) {
  let held = remote.heldWrites.contents[index];
  if (held === undefined) {
    return;
  }
  let next = Belt_Array.concatMany([remote.heldWrites.contents]);
  next.splice(index, 1);
  remote.heldWrites.contents = next;
  return held;
}

function makeRemote(onlineOpt, param) {
  let online = onlineOpt !== undefined ? onlineOpt : true;
  let network = Tilia.tilia({
    value: online
  });
  let activeFetches = {
    contents: 0
  };
  let doneFetches = {
    contents: 0
  };
  let offlineFetches = {
    contents: 0
  };
  let localFetches = {
    contents: 0
  };
  let upsertCalls = {
    contents: 0
  };
  let removeCalls = {
    contents: 0
  };
  let syncedWrites = {
    contents: []
  };
  let rejectedWrites = {
    contents: 0
  };
  let activeChannels = {
    contents: []
  };
  let heldWrites = {
    contents: []
  };
  let heldRemoves = {
    contents: []
  };
  let pausedWrites = {
    contents: false
  };
  let outcomes = {
    contents: {}
  };
  let nextFetches = {
    contents: {}
  };
  let remoteStore = {
    contents: {}
  };
  let localStore = {
    contents: {}
  };
  let queryStore = {
    contents: {}
  };
  let fetch = (query, channel) => {
    if (network.value) {
      let match = query.status;
      switch (match) {
        case "active" :
          activeFetches.contents = activeFetches.contents + 1 | 0;
          break;
        case "done" :
          doneFetches.contents = doneFetches.contents + 1 | 0;
          break;
      }
      let match$1 = query.status;
      if (match$1 === "active") {
        activeChannels.contents = Belt_Array.concatMany([
          activeChannels.contents,
          [channel]
        ]);
      }
      let match$2 = nextFetches.contents[query.status];
      if (match$2 !== undefined) {
        if (typeof match$2 !== "object") {
          Stdlib_Dict.$$delete(nextFetches.contents, query.status);
          channel.covered();
        } else {
          Stdlib_Dict.$$delete(nextFetches.contents, query.status);
          channel.fail(match$2._0);
        }
      } else {
        channel.emit(byStatus(remoteStore.contents, query.status));
      }
      return;
    }
    offlineFetches.contents = offlineFetches.contents + 1 | 0;
    channel.fail("offline");
  };
  let pullOutcome = value => {
    let values = outcomes.contents[value.id];
    if (values === undefined) {
      return {
        TAG: "Success",
        _0: value
      };
    }
    let head = values[0];
    if (head === undefined) {
      return {
        TAG: "Success",
        _0: value
      };
    }
    let tail = Belt_Array.concatMany([values]);
    tail.splice(0, 1);
    outcomes.contents[value.id] = tail;
    return head;
  };
  let transport = Tilia.tilia({
    online: Tilia.computed(() => network.value),
    fetch: fetch,
    upsert: (value, channel) => {
      upsertCalls.contents = upsertCalls.contents + 1 | 0;
      if (!network.value) {
        return channel.offline();
      }
      let outcome = pullOutcome(value);
      if (pausedWrites.contents) {
        heldWrites.contents = Belt_Array.concatMany([
          heldWrites.contents,
          [{
              value: value,
              outcome: outcome,
              channel: channel
            }]
        ]);
        return;
      } else {
        if (typeof outcome !== "object") {
          return channel.offline();
        }
        switch (outcome.TAG) {
          case "Success" :
            let saved = outcome._0;
            remoteStore.contents[saved.id] = saved;
            syncedWrites.contents = Belt_Array.concatMany([
              syncedWrites.contents,
              [saved]
            ]);
            return channel.emit(saved);
          case "Retry" :
            let server = outcome._0;
            remoteStore.contents[server.id] = server;
            return channel.conflict(server);
          case "Reject" :
            rejectedWrites.contents = rejectedWrites.contents + 1 | 0;
            return channel.reject(outcome._0);
        }
      }
    },
    remove: (value, channel) => {
      removeCalls.contents = removeCalls.contents + 1 | 0;
      if (!network.value) {
        return channel.offline();
      }
      let outcome = pullOutcome(value);
      if (pausedWrites.contents) {
        heldRemoves.contents = Belt_Array.concatMany([
          heldRemoves.contents,
          [{
              value: value,
              outcome: outcome,
              channel: channel
            }]
        ]);
        return;
      } else {
        if (typeof outcome !== "object") {
          return channel.offline();
        }
        switch (outcome.TAG) {
          case "Success" :
            let value$1 = outcome._0;
            Stdlib_Dict.$$delete(remoteStore.contents, value$1.id);
            syncedWrites.contents = Belt_Array.concatMany([
              syncedWrites.contents,
              [value$1]
            ]);
            return channel.emit(value$1);
          case "Retry" :
            let server = outcome._0;
            remoteStore.contents[server.id] = server;
            return channel.conflict(server);
          case "Reject" :
            rejectedWrites.contents = rejectedWrites.contents + 1 | 0;
            return channel.reject(outcome._0);
        }
      }
    }
  });
  let localApi_fetch = (query, channel) => {
    localFetches.contents = localFetches.contents + 1 | 0;
    let rows = Object.values(localStore.contents).filter(row => {
      if (row.deleted) {
        return false;
      } else {
        return row.item.name === query.status;
      }
    }).map(row => row.item);
    channel.emit(rows);
  };
  let localApi_save = (item, dirty) => {
    localStore.contents[item.id] = {
      item: item,
      dirty: dirty,
      deleted: false
    };
  };
  let localApi_remove = (item, dirty) => {
    if (dirty) {
      localStore.contents[item.id] = {
        item: item,
        dirty: true,
        deleted: true
      };
      return;
    } else {
      return Stdlib_Dict.$$delete(localStore.contents, item.id);
    }
  };
  let localApi_dirty = () => Promise.resolve(Object.values(localStore.contents).filter(row => row.dirty).map(row => ({
    value: row.item,
    deleted: row.deleted
  })));
  let localApi_queries = () => Promise.resolve(Object.values(queryStore.contents));
  let localApi_saveQuery = record => {
    queryStore.contents[record.key] = record;
  };
  let localApi_removeQuery = key => Stdlib_Dict.$$delete(queryStore.contents, key);
  let localApi = {
    fetch: localApi_fetch,
    save: localApi_save,
    remove: localApi_remove,
    dirty: localApi_dirty,
    queries: localApi_queries,
    saveQuery: localApi_saveQuery,
    removeQuery: localApi_removeQuery
  };
  return {
    api: transport,
    localApi: localApi,
    network: network,
    activeFetches: activeFetches,
    doneFetches: doneFetches,
    offlineFetches: offlineFetches,
    localFetches: localFetches,
    upsertCalls: upsertCalls,
    removeCalls: removeCalls,
    syncedWrites: syncedWrites,
    rejectedWrites: rejectedWrites,
    activeChannels: activeChannels,
    heldWrites: heldWrites,
    heldRemoves: heldRemoves,
    pausedWrites: pausedWrites,
    outcomes: outcomes,
    nextFetches: nextFetches,
    remoteStore: remoteStore,
    localStore: localStore,
    queryStore: queryStore
  };
}

function id(item) {
  return item.id;
}

function makeItems(clock, remote) {
  return make("items", id, remote.api, remote.localApi, 30.0, 300.0, () => clock.contents, (query, changed) => changed.name === query.status, (a, b) => a.id.localeCompare(b.id));
}

function makeWorld() {
  Vitest.vi.useFakeTimers();
  let clock = {
    contents: 0.0
  };
  let remote = makeRemote(undefined, undefined);
  return {
    clock: clock,
    remote: remote,
    items: makeItems(clock, remote)
  };
}

function restart(w) {
  w.items = makeItems(w.clock, w.remote);
  return Promise.resolve().then(() => Promise.resolve());
}

function seed(w, items) {
  w.remote.remoteStore.contents = fromItems(items);
  w.remote.activeFetches.contents = 0;
  w.remote.doneFetches.contents = 0;
  w.remote.offlineFetches.contents = 0;
  w.remote.localFetches.contents = 0;
  w.remote.upsertCalls.contents = 0;
  w.remote.removeCalls.contents = 0;
  w.remote.syncedWrites.contents = [];
  w.remote.rejectedWrites.contents = 0;
  w.remote.activeChannels.contents = [];
  w.remote.heldWrites.contents = [];
  w.remote.heldRemoves.contents = [];
  w.remote.pausedWrites.contents = false;
  w.remote.outcomes.contents = {};
  w.remote.nextFetches.contents = {};
  w.remote.localStore.contents = {};
  w.remote.queryStore.contents = {};
}

function setNetwork(w, online) {
  w.remote.network.value = online;
}

function remoteTask(w, id) {
  return get(w.remote.remoteStore.contents, id);
}

function seedLocal(w, id, status, count, dirty) {
  w.remote.localStore.contents[id] = {
    item: {
      id: id,
      name: status,
      count: count
    },
    dirty: dirty,
    deleted: false
  };
}

function seedLocalTombstone(w, id, status, count) {
  w.remote.localStore.contents[id] = {
    item: {
      id: id,
      name: status,
      count: count
    },
    dirty: true,
    deleted: true
  };
}

function localTask(w, id) {
  let row = w.remote.localStore.contents[id];
  if (row !== undefined) {
    return row;
  } else {
    return Pervasives.failwith("Expected task in local store");
  }
}

function localRow(w, id) {
  return w.remote.localStore.contents[id];
}

function remoteRow(w, id) {
  return w.remote.remoteStore.contents[id];
}

function deleteOnServer(w, id) {
  Stdlib_Dict.$$delete(w.remote.remoteStore.contents, id);
}

function seedQueryRecord(w, key, ids) {
  w.remote.queryStore.contents[key] = {
    key: key,
    ids: ids,
    fetched: 0.0
  };
}

function queryRecord(w, key) {
  return w.remote.queryStore.contents[key];
}

function localFetchCount(w) {
  return w.remote.localFetches.contents;
}

function queueConflict(w, id, status, count) {
  pushOutcome(w.remote, id, {
    TAG: "Retry",
    _0: {
      id: id,
      name: status,
      count: count
    }
  });
}

function queueRejected(w, id, message) {
  pushOutcome(w.remote, id, {
    TAG: "Reject",
    _0: message
  });
}

function queueOffline(w, id) {
  pushOutcome(w.remote, id, "Drop");
}

function queueCoveredFetch(w, status) {
  w.remote.nextFetches.contents[status] = "CoveredFetch";
}

function queueFailFetch(w, status, message) {
  w.remote.nextFetches.contents[status] = {
    TAG: "FailFetch",
    _0: message
  };
}

function pauseWrites(w, paused) {
  w.remote.pausedWrites.contents = paused;
}

function takeHeldRemove(remote, index) {
  let held = remote.heldRemoves.contents[index];
  if (held === undefined) {
    return;
  }
  let next = Belt_Array.concatMany([remote.heldRemoves.contents]);
  next.splice(index, 1);
  remote.heldRemoves.contents = next;
  return held;
}

function emitHeldRemove(w, index) {
  let held = takeHeldRemove(w.remote, index);
  if (held !== undefined) {
    Stdlib_Dict.$$delete(w.remote.remoteStore.contents, held.value.id);
    w.remote.syncedWrites.contents = Belt_Array.concatMany([
      w.remote.syncedWrites.contents,
      [held.value]
    ]);
    return held.channel.emit(held.value);
  }
}

function emitHeldWrite(w, index, count) {
  let held = takeHeld(w.remote, index);
  if (held === undefined) {
    return;
  }
  let value_id = held.value.id;
  let value_name = held.value.name;
  let value = {
    id: value_id,
    name: value_name,
    count: count
  };
  w.remote.remoteStore.contents[value_id] = value;
  w.remote.syncedWrites.contents = Belt_Array.concatMany([
    w.remote.syncedWrites.contents,
    [value]
  ]);
  held.channel.emit(value);
}

function heldWrites(w) {
  return w.remote.heldWrites.contents.length;
}

function emitActiveChannel(w, index, count) {
  let channel = w.remote.activeChannels.contents[index];
  if (channel !== undefined) {
    return channel.emit([{
        id: "todo-1",
        name: "active",
        count: count
      }]);
  }
}

let Channel;

export {
  item,
  Channel,
  Papabase,
  Store,
  Runtime,
  pushOutcome,
  takeHeld,
  makeRemote,
  id,
  makeItems,
  makeWorld,
  restart,
  seed,
  setNetwork,
  remoteTask,
  seedLocal,
  seedLocalTombstone,
  localTask,
  localRow,
  remoteRow,
  deleteOnServer,
  seedQueryRecord,
  queryRecord,
  localFetchCount,
  queueConflict,
  queueRejected,
  queueOffline,
  queueCoveredFetch,
  queueFailFetch,
  pauseWrites,
  takeHeldRemove,
  emitHeldRemove,
  emitHeldWrite,
  heldWrites,
  emitActiveChannel,
}
/* Tilia Not a pure module */
