// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Vitest from "vitest";
import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as VitestBdd from "vitest-bdd";
import * as TiliaQueryTestHelpers from "./TiliaQueryTestHelpers.mjs";

function parse(value) {
  let count = Stdlib_Int.fromString(value, undefined);
  if (count !== undefined) {
    return count;
  } else {
    return Pervasives.failwith("Expected number");
  }
}

function task(row) {
  return TiliaQueryTestHelpers.item(row.id, row.status, parse(row.count));
}

VitestBdd.Given("a task world", (param, param$1) => {
  let step = param.step;
  let w = TiliaQueryTestHelpers.makeWorld();
  step("tasks are", table => {
    let rows = VitestBdd.toRecords(table);
    TiliaQueryTestHelpers.seed(w, rows.map(task));
  });
  step("network is {string}", mode => {
    switch (mode) {
      case "offline" :
        w.remote.online.contents = false;
        return;
      case "online" :
        w.remote.online.contents = true;
        return;
      default:
        return Pervasives.failwith("Unknown network mode");
    }
  });
  step("network becomes {string}", mode => {
    switch (mode) {
      case "offline" :
        w.remote.online.contents = false;
        return;
      case "online" :
        w.remote.online.contents = true;
        let queued = w.remote.pendingWrites.contents;
        w.remote.syncPending();
        queued.forEach(w.items.sync);
        return w.items.tick();
      default:
        return Pervasives.failwith("Unknown network mode");
    }
  });
  step("I open {string} tasks", list => {
    switch (list) {
      case "active" :
        return Tilia.watch(() => w.items.array({
          status: "active"
        }), param => {});
      case "active and done" :
        Tilia.watch(() => w.items.array({
          status: "active"
        }), param => {});
        return Tilia.watch(() => w.items.array({
          status: "done"
        }), param => {});
      case "done" :
        return Tilia.watch(() => w.items.array({
          status: "done"
        }), param => {});
      default:
        return Pervasives.failwith("Unknown tasks list");
    }
  });
  step("I edit task {string} to status {string} count {number}", (id, status, count) => w.items.upsert(TiliaQueryTestHelpers.item(id, status, count)));
  step("I sync pending writes", () => {
    let queued = w.remote.pendingWrites.contents;
    w.remote.syncPending();
    queued.forEach(w.items.sync);
    w.items.tick();
  });
  step("I run tick for {string} tasks after {number} seconds", (target, seconds) => {
    w.clock.contents = w.clock.contents + seconds;
    switch (target) {
      case "active" :
      case "active and done" :
      case "done" :
        return w.items.tick();
      default:
        return Pervasives.failwith("Unknown tick target");
    }
  });
  step("I emit from active fetch channel {number} with count {number}", (position, count) => {
    let index = position <= 0 ? 0 : position - 1 | 0;
    TiliaQueryTestHelpers.emitActiveChannel(w, index, count);
  });
  step("{string} tasks should be", (status, table) => {
    let rows = VitestBdd.toRecords(table);
    Vitest.expect(w.items.array({
      status: status
    })).toEqual({
      TAG: "Loaded",
      _0: rows.map(task)
    });
  });
  step("no {string} tasks should remain", status => Vitest.expect(w.items.array({
    status: status
  })).toEqual({
    TAG: "Loaded",
    _0: []
  }));
  step("task {string} in cache should be status {string} count {number}", (id, status, count) => Vitest.expect(w.items.get(id)).toEqual({
    TAG: "Loaded",
    _0: TiliaQueryTestHelpers.item(id, status, count)
  }));
  step("remote task {string} should be status {string} count {number}", (id, status, count) => Vitest.expect(TiliaQueryTestHelpers.remoteTask(w, id)).toEqual(TiliaQueryTestHelpers.item(id, status, count)));
  step("pending sync writes should be {number}", expected => Vitest.expect(w.remote.pendingWrites.contents.length).toBe(expected));
  step("synced remote writes should be {number}", expected => Vitest.expect(w.remote.syncedWrites.contents.length).toBe(expected));
  step("{string} fetch calls should be {number}", (name, expected) => {
    let tmp;
    switch (name) {
      case "active" :
        tmp = w.remote.activeFetches.contents;
        break;
      case "done" :
        tmp = w.remote.doneFetches.contents;
        break;
      case "offline" :
        tmp = w.remote.offlineFetches.contents;
        break;
      default:
        tmp = Pervasives.failwith("Unknown fetch metric");
    }
    Vitest.expect(tmp).toBe(expected);
  });
});

let H;

let item = TiliaQueryTestHelpers.item;

export {
  H,
  item,
  parse,
  task,
}
/*  Not a pure module */
