// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Vitest from "vitest";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";
import * as TiliaQuery from "../src/TiliaQuery.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function item(id, name, count) {
  return {
    id: id,
    name: name,
    count: count
  };
}

function make(_table, id, remote, stale, gc, now, invalidates) {
  return TiliaQuery.make(id, remote, stale, gc, now, undefined, invalidates, undefined);
}

let Papabase = {
  make: make
};

function fromItems(items) {
  let dict = {};
  items.forEach(item => {
    dict[item.id] = item;
  });
  return dict;
}

function get(dict, id) {
  let value = dict[id];
  if (value !== undefined) {
    return Primitive_option.valFromOption(value);
  } else {
    return Pervasives.failwith("Expected task in store");
  }
}

function byStatus(dict, status) {
  return Object.entries(dict).map(param => param[1]).filter(item => item.name === status);
}

let Store = {
  fromItems: fromItems,
  get: get,
  byStatus: byStatus
};

let Runtime = {};

function pushOutcome(remote, id, outcome) {
  let values = remote.outcomes.contents[id];
  if (values !== undefined) {
    remote.outcomes.contents[id] = Belt_Array.concatMany([
      values,
      [outcome]
    ]);
  } else {
    remote.outcomes.contents[id] = [outcome];
  }
}

function takeHeld(remote, index) {
  let held = remote.heldWrites.contents[index];
  if (held === undefined) {
    return;
  }
  let next = Belt_Array.concatMany([remote.heldWrites.contents]);
  next.splice(index, 1);
  remote.heldWrites.contents = next;
  return held;
}

function makeRemote(onlineOpt, param) {
  let online = onlineOpt !== undefined ? onlineOpt : true;
  let network = Tilia.tilia({
    value: online
  });
  let activeFetches = {
    contents: 0
  };
  let doneFetches = {
    contents: 0
  };
  let offlineFetches = {
    contents: 0
  };
  let upsertCalls = {
    contents: 0
  };
  let syncedWrites = {
    contents: []
  };
  let rejectedWrites = {
    contents: 0
  };
  let activeChannels = {
    contents: []
  };
  let heldWrites = {
    contents: []
  };
  let pausedWrites = {
    contents: false
  };
  let outcomes = {
    contents: {}
  };
  let remoteStore = {
    contents: {}
  };
  let fetch = (query, channel) => {
    if (network.value) {
      let match = query.status;
      switch (match) {
        case "active" :
          activeFetches.contents = activeFetches.contents + 1 | 0;
          break;
        case "done" :
          doneFetches.contents = doneFetches.contents + 1 | 0;
          break;
      }
      let rows = byStatus(remoteStore.contents, query.status);
      let match$1 = query.status;
      if (match$1 === "active") {
        activeChannels.contents = Belt_Array.concatMany([
          activeChannels.contents,
          [channel]
        ]);
      }
      channel.emit(rows);
      return;
    }
    offlineFetches.contents = offlineFetches.contents + 1 | 0;
    channel.fail("offline");
  };
  let pullOutcome = value => {
    let values = outcomes.contents[value.id];
    if (values === undefined) {
      return {
        TAG: "Success",
        _0: value
      };
    }
    let head = values[0];
    if (head === undefined) {
      return {
        TAG: "Success",
        _0: value
      };
    }
    let tail = Belt_Array.concatMany([values]);
    tail.splice(0, 1);
    outcomes.contents[value.id] = tail;
    return head;
  };
  let applyOutcome = (channel, outcome) => {
    if (typeof outcome !== "object") {
      return channel.fail("Offline");
    }
    switch (outcome.TAG) {
      case "Success" :
        let saved = outcome._0;
        remoteStore.contents[saved.id] = saved;
        syncedWrites.contents = Belt_Array.concatMany([
          syncedWrites.contents,
          [saved]
        ]);
        return channel.emit(saved);
      case "Retry" :
        let server = outcome._0;
        remoteStore.contents[server.id] = server;
        return channel.fail({
          TAG: "Conflict",
          _0: server
        });
      case "Reject" :
        rejectedWrites.contents = rejectedWrites.contents + 1 | 0;
        return channel.fail({
          TAG: "Rejected",
          _0: outcome._0
        });
    }
  };
  let transport = Tilia.tilia({
    online: Tilia.computed(() => network.value),
    fetch: fetch,
    upsert: (value, channel) => {
      upsertCalls.contents = upsertCalls.contents + 1 | 0;
      if (network.value) {
        let outcome = pullOutcome(value);
        if (pausedWrites.contents) {
          heldWrites.contents = Belt_Array.concatMany([
            heldWrites.contents,
            [{
                value: value,
                outcome: outcome,
                channel: channel
              }]
          ]);
        } else {
          applyOutcome(channel, outcome);
        }
      } else {
        channel.fail("Offline");
      }
    }
  });
  return {
    api: transport,
    network: network,
    activeFetches: activeFetches,
    doneFetches: doneFetches,
    offlineFetches: offlineFetches,
    upsertCalls: upsertCalls,
    syncedWrites: syncedWrites,
    rejectedWrites: rejectedWrites,
    activeChannels: activeChannels,
    heldWrites: heldWrites,
    pausedWrites: pausedWrites,
    outcomes: outcomes,
    remoteStore: remoteStore
  };
}

function makeWorld() {
  Vitest.vi.useFakeTimers();
  let clock = {
    contents: 0.0
  };
  let remote = makeRemote(undefined, undefined);
  let id = item => item.id;
  let items = make("items", id, remote.api, 30.0, 300.0, () => clock.contents, (query, changed) => {
    if (query.status === "active") {
      return true;
    } else {
      return query.status === changed.name;
    }
  });
  return {
    clock: clock,
    remote: remote,
    items: items
  };
}

function seed(w, items) {
  w.remote.remoteStore.contents = fromItems(items);
  w.remote.activeFetches.contents = 0;
  w.remote.doneFetches.contents = 0;
  w.remote.offlineFetches.contents = 0;
  w.remote.upsertCalls.contents = 0;
  w.remote.syncedWrites.contents = [];
  w.remote.rejectedWrites.contents = 0;
  w.remote.activeChannels.contents = [];
  w.remote.heldWrites.contents = [];
  w.remote.pausedWrites.contents = false;
  w.remote.outcomes.contents = {};
}

function setNetwork(w, online) {
  w.remote.network.value = online;
}

function remoteTask(w, id) {
  return get(w.remote.remoteStore.contents, id);
}

function queueConflict(w, id, status, count) {
  pushOutcome(w.remote, id, {
    TAG: "Retry",
    _0: {
      id: id,
      name: status,
      count: count
    }
  });
}

function queueRejected(w, id, message) {
  pushOutcome(w.remote, id, {
    TAG: "Reject",
    _0: message
  });
}

function queueOffline(w, id) {
  pushOutcome(w.remote, id, "Drop");
}

function pauseWrites(w, paused) {
  w.remote.pausedWrites.contents = paused;
}

function emitHeldWrite(w, index, count) {
  let held = takeHeld(w.remote, index);
  if (held === undefined) {
    return;
  }
  let value_id = held.value.id;
  let value_name = held.value.name;
  let value = {
    id: value_id,
    name: value_name,
    count: count
  };
  w.remote.remoteStore.contents[value_id] = value;
  w.remote.syncedWrites.contents = Belt_Array.concatMany([
    w.remote.syncedWrites.contents,
    [value]
  ]);
  held.channel.emit(value);
}

function heldWrites(w) {
  return w.remote.heldWrites.contents.length;
}

function emitActiveChannel(w, index, count) {
  let channel = w.remote.activeChannels.contents[index];
  if (channel !== undefined) {
    return channel.emit([{
        id: "todo-1",
        name: "active",
        count: count
      }]);
  }
}

let Channel;

export {
  item,
  Channel,
  Papabase,
  Store,
  Runtime,
  pushOutcome,
  takeHeld,
  makeRemote,
  makeWorld,
  seed,
  setNetwork,
  remoteTask,
  queueConflict,
  queueRejected,
  queueOffline,
  pauseWrites,
  emitHeldWrite,
  heldWrites,
  emitActiveChannel,
}
/* Tilia Not a pure module */
