// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";
import * as TiliaQuery from "../src/TiliaQuery.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function item(id, name, count) {
  return {
    id: id,
    name: name,
    count: count
  };
}

function make(_table, id, api, stale, gc, now, invalidates) {
  return TiliaQuery.make(id, api.fetch, api.upsert, stale, gc, now, undefined, invalidates, undefined);
}

let Papabase = {
  make: make
};

function fromItems(items) {
  let dict = {};
  items.forEach(item => {
    dict[item.id] = item;
  });
  return dict;
}

function get(dict, id) {
  let value = dict[id];
  if (value !== undefined) {
    return Primitive_option.valFromOption(value);
  } else {
    return Pervasives.failwith("Expected task in store");
  }
}

function byStatus(dict, status) {
  return Object.entries(dict).map(param => param[1]).filter(item => item.name === status);
}

let Store = {
  fromItems: fromItems,
  get: get,
  byStatus: byStatus
};

let Runtime = {};

function makeRemote(onlineOpt, param) {
  let online = onlineOpt !== undefined ? onlineOpt : true;
  let online$1 = {
    contents: online
  };
  let activeFetches = {
    contents: 0
  };
  let doneFetches = {
    contents: 0
  };
  let offlineFetches = {
    contents: 0
  };
  let pendingWrites = {
    contents: []
  };
  let syncedWrites = {
    contents: []
  };
  let activeChannels = {
    contents: []
  };
  let localStore = {
    contents: {}
  };
  let remoteStore = {
    contents: {}
  };
  let fetch = (query, channel) => {
    if (online$1.contents) {
      let match = query.status;
      switch (match) {
        case "active" :
          activeFetches.contents = activeFetches.contents + 1 | 0;
          break;
        case "done" :
          doneFetches.contents = doneFetches.contents + 1 | 0;
          break;
      }
      let rows = byStatus(remoteStore.contents, query.status);
      let match$1 = query.status;
      if (match$1 === "active") {
        activeChannels.contents = Belt_Array.concatMany([
          activeChannels.contents,
          [channel]
        ]);
      }
      channel.emit(rows);
      return;
    }
    offlineFetches.contents = offlineFetches.contents + 1 | 0;
    let rows$1 = byStatus(localStore.contents, query.status);
    channel.emit(rows$1);
  };
  let upsert = (value, channel) => {
    localStore.contents[value.id] = value;
    if (online$1.contents) {
      remoteStore.contents[value.id] = value;
      syncedWrites.contents = Belt_Array.concatMany([
        syncedWrites.contents,
        [value]
      ]);
    } else {
      pendingWrites.contents = Belt_Array.concatMany([
        pendingWrites.contents,
        [value]
      ]);
    }
    channel.emit();
  };
  let syncPending = () => {
    if (online$1.contents) {
      pendingWrites.contents.forEach(value => {
        remoteStore.contents[value.id] = value;
        syncedWrites.contents = Belt_Array.concatMany([
          syncedWrites.contents,
          [value]
        ]);
      });
      pendingWrites.contents = [];
      return;
    }
  };
  return {
    api: {
      fetch: fetch,
      upsert: upsert
    },
    online: online$1,
    activeFetches: activeFetches,
    doneFetches: doneFetches,
    offlineFetches: offlineFetches,
    pendingWrites: pendingWrites,
    syncedWrites: syncedWrites,
    activeChannels: activeChannels,
    localStore: localStore,
    remoteStore: remoteStore,
    syncPending: syncPending
  };
}

function makeWorld() {
  Vitest.vi.useFakeTimers();
  let clock = {
    contents: 0.0
  };
  let remote = makeRemote(undefined, undefined);
  let id = item => item.id;
  let items = make("items", id, remote.api, 30.0, 300.0, () => clock.contents, (query, changed) => {
    if (query.status === "active") {
      return true;
    } else {
      return query.status === changed.name;
    }
  });
  return {
    clock: clock,
    remote: remote,
    items: items
  };
}

function seed(w, items) {
  let initial = fromItems(items);
  w.remote.localStore.contents = initial;
  w.remote.remoteStore.contents = fromItems(items);
  w.remote.activeFetches.contents = 0;
  w.remote.doneFetches.contents = 0;
  w.remote.offlineFetches.contents = 0;
  w.remote.pendingWrites.contents = [];
  w.remote.syncedWrites.contents = [];
  w.remote.activeChannels.contents = [];
}

function remoteTask(w, id) {
  return get(w.remote.remoteStore.contents, id);
}

function emitActiveChannel(w, index, count) {
  let channel = w.remote.activeChannels.contents[index];
  if (channel !== undefined) {
    return channel.emit([{
        id: "todo-1",
        name: "active",
        count: count
      }]);
  }
}

export {
  item,
  Papabase,
  Store,
  Runtime,
  makeRemote,
  makeWorld,
  seed,
  remoteTask,
  emitActiveChannel,
}
/* vitest Not a pure module */
