// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Vitest from "vitest";
import * as MakeWorld from "./MakeWorld.mjs";
import * as VitestBdd from "vitest-bdd";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

VitestBdd.Given("an {string} training app", (param, status) => {
  let step = param.step;
  let match = Tilia.signal(status === "online");
  let setOnline = match[1];
  let match$1 = Tilia.signal(0.0);
  let setNow = match$1[1];
  let now_ = match$1[0];
  let network = MakeWorld.Network.make();
  let papabase = MakeWorld.Papabase.make(network);
  let dexme = MakeWorld.Dexme.make();
  let cards = MakeWorld.make(dexme, papabase, () => now_.value, match[0]);
  let view = {
    contents: "loading"
  };
  let closeDeck = {
    contents: () => {}
  };
  step("a set of language cards on a remote", table => {
    VitestBdd.toRecords(table).forEach(card => {
      papabase.upsert(card);
    });
  });
  step("the remote is updated with", table => {
    VitestBdd.toRecords(table).forEach(card => {
      papabase.upsert(card);
    });
  });
  let advanceClock = ms => {
    setNow(now_.value + ms);
    network.flush();
  };
  step("time passes", () => advanceClock(1.0));
  step("{number} minutes pass", minutes => advanceClock(minutes * 60.0 * 1000.0));
  step("{number} seconds pass", seconds => advanceClock(seconds * 1000.0));
  step("{number} days pass", days => advanceClock(days * 86400000.0));
  step("tick is called", cards.tick);
  step("a local cache of cards", table => {
    VitestBdd.toRecords(table).forEach(card => {
      dexme.cards.put(card);
    });
  });
  step("I go {string}", status => setOnline(status === "online"));
  step("I open the {string} deck", deck => {
    let query = {
      deck: deck.toLowerCase()
    };
    closeDeck.contents = Tilia.observe(() => {
      view.contents = cards.array(query);
      let match = view.contents;
      if (typeof match !== "object") {
        console.log("not loaded");
        return;
      }
      if (match.state === "loaded") {
        console.log(match.data);
        return;
      }
      console.log("not loaded");
    });
  });
  step("I close the deck", () => closeDeck.contents());
  step("I should see loading", () => Vitest.expect(view.contents).toMatchObject("loading"));
  step("I should see not local", () => Vitest.expect(view.contents).toMatchObject("notLocal"));
  step("I should see {string} loaded with data", (local, table) => {
    let expected = VitestBdd.toRecords(table);
    Vitest.expect(view.contents).toMatchObject({
      state: "loaded",
      data: expected,
      local: local === "local"
    });
  });
  step("I upsert", table => {
    VitestBdd.toRecords(table).forEach(card => cards.upsert(card));
  });
  step("remote should have", table => {
    VitestBdd.toRecords(table).forEach(card => {
      let found = Stdlib_Option.getOrThrow(papabase._select(c => c.id === card.id)[0], `remote has no card "` + card.id + `"`);
      Vitest.expect(found).toMatchObject(card);
    });
  });
  step("local should not have {string}", id => Vitest.expect(dexme.cards._select(c => c.id === id).length).toBe(0));
  step("local should have", table => {
    VitestBdd.toRecords(table).forEach(card => {
      let found = Stdlib_Option.getOrThrow(dexme.cards._select(c => c.id === card.id)[0], `local has no card "` + card.id + `"`);
      Vitest.expect(found).toMatchObject(card);
    });
  });
});

/*  Not a pure module */
