packages:
  - tilia
  - react
  - todo-app-ts
  - website
  - performance
  - tests/app1
  - tests/app2
  - tests/app3
  - tests/app4

overrides:
  astro@<5.14.3: '>=5.14.3'
  astro@<5.15.8: '>=5.15.8'
  astro@<5.15.9: '>=5.15.9'
  astro@<=5.15.6: '>=5.15.8'
  astro@>=2.16.0 <5.15.5: '>=5.15.5'
  astro@>=5.0.0-alpha.0 <5.13.2: '>=5.13.2'
  astro@>=5.2.0 <5.12.8: '>=5.12.8'
  astro@>=5.2.0 <5.15.6: '>=5.15.6'
  devalue@<5.3.2: '>=5.3.2'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'
