// Generated by ReScript, PLEASE EDIT WITH CARE

import Ava from "ava";
import * as TiliaCore from "../src/TiliaCore.mjs";

var make = (() => ({}));

var $$Object = {
  make: make
};

Ava("should track leaf changes", (function (t) {
        var m = {
          called: false
        };
        var p = {
          name: "John",
          username: "jo"
        };
        var r = TiliaCore.make(p);
        var x = r[1];
        var o = TiliaCore._connect(r, (function () {
                m.called = true;
              }));
        t.is(x.name, "John");
        t.is(m.called, false);
        x.name = "One";
        t.is(m.called, false);
        TiliaCore._flush(o);
        x.name = "One";
        t.is(m.called, false);
        x.name = "Two";
        t.is(m.called, true);
        m.called = false;
        x.name = "Three";
        t.is(m.called, false);
      }));

Ava("should observe", (function (t) {
        var p = {
          name: "John",
          username: "jo"
        };
        var r = TiliaCore.make(p);
        TiliaCore.observe(r, (function (p) {
                p.username = p.name.toLowerCase().slice(0, 2);
              }));
        var p$1 = r[1];
        t.is(p$1.username, "jo");
        p$1.name = "John";
        t.is(p$1.username, "jo");
        p$1.name = "Mary";
        t.is(p$1.username, "ma");
      }));

Ava("should allow mutating observed", (function (t) {
        var p = {
          name: "John",
          username: "jo"
        };
        var r = TiliaCore.make(p);
        TiliaCore.observe(r, (function (p) {
                p.name = p.name.toLowerCase().slice(0, 2);
              }));
        var p$1 = r[1];
        t.is(p$1.name, "jo");
        p$1.name = "John";
        t.is(p$1.name, "jo");
        p$1.name = "Mary";
        t.is(p$1.name, "ma");
      }));

Ava("should proxy sub-objects", (function (t) {
        var m = {
          called: false
        };
        var p = {
          name: "John",
          address: {
            city: "Love",
            zip: 1234
          },
          passions: [],
          notes: make()
        };
        var r = TiliaCore.make(p);
        var x = r[1];
        var o = TiliaCore._connect(r, (function () {
                m.called = true;
              }));
        t.is(x.address.city, "Love");
        t.is(m.called, false);
        x.address.city = "Passion";
        t.is(m.called, false);
        TiliaCore._flush(o);
        x.address.city = "Passion";
        t.is(m.called, false);
        x.address.city = "Kindness";
        t.is(m.called, true);
        m.called = false;
        x.address.city = "Sorrow";
        t.is(m.called, false);
      }));

Ava("should proxy array", (function (t) {
        var m = {
          called: false
        };
        var p = {
          name: "John",
          address: {
            city: "Love",
            zip: 1234
          },
          passions: ["fruits"],
          notes: make()
        };
        var r = TiliaCore.make(p);
        var x = r[1];
        var o = TiliaCore._connect(r, (function () {
                m.called = true;
              }));
        t.is(x.passions[0], "fruits");
        TiliaCore._flush(o);
        x.passions[0] = "watercolor";
        t.is(m.called, true);
      }));

Ava("should watch array index", (function (t) {
        var m = {
          called: false
        };
        var p = {
          name: "John",
          address: {
            city: "Love",
            zip: 1234
          },
          passions: ["fruits"],
          notes: make()
        };
        var r = TiliaCore.make(p);
        var x = r[1];
        var o = TiliaCore._connect(r, (function () {
                m.called = true;
              }));
        t.is(x.passions.length, 1);
        TiliaCore._flush(o);
        x.passions.push("watercolor");
        t.is(m.called, true);
      }));

Ava("should watch object keys", (function (t) {
        var m = {
          called: false
        };
        var p = {
          name: "John",
          address: {
            city: "Love",
            zip: 1234
          },
          passions: ["fruits"],
          notes: make()
        };
        var r = TiliaCore.make(p);
        var x = r[1];
        var o = TiliaCore._connect(r, (function () {
                m.called = true;
              }));
        t.is(Object.keys(x.notes).length, 0);
        TiliaCore._flush(o);
        Reflect.set(x.notes, "2024-12-07", "Rebuilding Tilia in ReScript");
        t.is(m.called, true);
      }));

var Core;

export {
  Core ,
  $$Object ,
}
/*  Not a pure module */
