// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CounterTs from "./counter.ts";

var counter = CounterTs.counter;

function testCounter() {
  ((counter.value = 0));
  ((counter.increment()));
  ((counter.increment()));
  return counter.value === 2;
}

function testDouble() {
  ((counter.value = 5));
  return counter.double === 10;
}

function testDecrement() {
  ((counter.value = 10));
  ((counter.decrement()));
  return counter.value === 9;
}

export {
  counter ,
  testCounter ,
  testDouble ,
  testDecrement ,
}
/* counter Not a pure module */
