// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";

function makeTodo(id, title) {
  return {
          id: id,
          title: title,
          completed: false
        };
}

function add(self) {
  return function (todo) {
    self.list.push(todo);
  };
}

function toggle(self) {
  return function (id) {
    var t = self.list.find(function (t) {
          return t.id === id;
        });
    if (t !== undefined) {
      t.completed = !t.completed;
      return ;
    }
    
  };
}

function remove(self) {
  return function (id) {
    self.list = self.list.filter(function (todo) {
          return todo.id !== id;
        });
  };
}

function completedCount(self) {
  return self.list.filter(function (todo) {
              return todo.completed;
            }).length;
}

function make() {
  return Tilia.carve(function (param) {
              var derived = param.derived;
              return {
                      list: [],
                      add: derived(add),
                      toggle: derived(toggle),
                      remove: derived(remove),
                      completedCount: derived(completedCount)
                    };
            });
}

export {
  makeTodo ,
  add ,
  toggle ,
  remove ,
  completedCount ,
  make ,
}
/* Tilia Not a pure module */
