// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as Counter from "../domain/Counter.res.mjs";
import * as VitestBdd from "vitest-bdd";

VitestBdd.Given("counter is initialized", (function (param, param$1) {
        var step = param.step;
        var counter = Counter.make();
        step("I increment the counter", (function () {
                counter.increment();
              }));
        step("I decrement the counter", (function () {
                counter.decrement();
              }));
        step("I set counter to {number}", (function (value) {
                counter.value = value;
              }));
        step("counter value should be {number}", (function (expected) {
                Vitest.expect(counter.value).toBe(expected);
              }));
        step("counter double should be {number}", (function (expected) {
                Vitest.expect(counter.double).toBe(expected);
              }));
        step("counter should notify observers on change", (function () {
                var values = [];
                Counter.observeCounter(counter, (function (value) {
                        values.push(value);
                      }));
                counter.value = 10.0;
                counter.value = 20.0;
                Vitest.expect(values).toEqual([
                      0.0,
                      10.0,
                      20.0
                    ]);
              }));
      }));

export {
  
}
/*  Not a pure module */
