// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as React from "react";

function use(p) {
  var match = React.useState(0);
  var setCount = match[1];
  var o = Tilia._observe(p, (function () {
          setCount(function (i) {
                return i + 1 | 0;
              });
        }));
  React.useEffect(function () {
        Tilia._ready(o, undefined);
        return (function () {
                  Tilia.clear(o);
                });
      });
  return p;
}

export {
  use ,
}
/* Tilia Not a pure module */
