// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TiliaCore from "@tilia/core/src/TiliaCore.mjs";

function use(p) {
  var match = React.useState(0);
  var setCount = match[1];
  var o = TiliaCore._connect(p, (function () {
          setCount(function (i) {
                return i + 1 | 0;
              });
        }));
  React.useEffect(function () {
        TiliaCore._ready(o, undefined);
        return (function () {
                  TiliaCore.clear(o);
                });
      });
  return p;
}

var make = TiliaCore.make;

var observe = TiliaCore.observe;

var compute = TiliaCore.compute;

var track = TiliaCore.track;

var clear = TiliaCore.clear;

export {
  make ,
  observe ,
  compute ,
  track ,
  clear ,
  use ,
}
/* react Not a pure module */
