// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as React from "react";

function make(ctx) {
  let _observe = ctx._observe;
  let tilia = ctx.tilia;
  let useTilia = () => {
    let match = React.useState(0);
    let setCount = match[1];
    let o = _observe(() => setCount(i => i + 1 | 0));
    React.useEffect(() => {
      Tilia._ready(o, true);
      return () => Tilia._clear(o);
    });
  };
  let useComputed = fn => React.useMemo(() => tilia({
    value: Tilia.computed(fn)
  }), []).value;
  let leaf = fn => (p => {
    let match = React.useState(0);
    let setCount = match[1];
    let o = _observe(() => setCount(i => i + 1 | 0));
    React.useEffect(() => {
      Tilia._ready(o, true);
      return () => Tilia._clear(o);
    });
    let node = fn(p);
    Tilia._done(o);
    return node;
  });
  return {
    useTilia: useTilia,
    useComputed: useComputed,
    leaf: leaf
  };
}

let tr = make(Tilia._ctx);

let useTilia = tr.useTilia;

let useComputed = tr.useComputed;

let leaf = tr.leaf;

export {
  useTilia,
  useComputed,
  leaf,
  make,
}
/* tr Not a pure module */
