// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

var ClassList = {};

function Blink(props) {
  var ref = React.useRef(null);
  React.useEffect(function () {
        var dom = ref.current;
        if (dom === null || dom === undefined) {
          dom === null;
        } else {
          dom.classList.add("bg-green-200");
          setTimeout((function () {
                  dom.classList.remove("bg-green-200");
                }), 150);
        }
      });
  return JsxRuntime.jsx("div", {
              children: props.children,
              ref: Caml_option.some(ref),
              className: "rounded-md"
            });
}

var make = Blink;

export {
  ClassList ,
  make ,
}
/* react Not a pure module */
