// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TiliaCore from "./TiliaCore.res.mjs";

function use(p) {
  console.log("RENDER");
  var match = React.useState(0);
  var setCount = match[1];
  var o = TiliaCore._connect(p, (function () {
          console.log("REDRAW");
          setCount(function (i) {
                return i + 1 | 0;
              });
        }));
  React.useEffect(function () {
        console.log("REACT FLUSH");
        TiliaCore._flush(o);
        return (function () {
                  TiliaCore._clear(o);
                });
      });
  return p;
}

var make = TiliaCore.make;

var observe = TiliaCore.observe;

export {
  make ,
  observe ,
  use ,
}
/* react Not a pure module */
