// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TiliaCore from "./TiliaCore.res.mjs";

function _inc(i) {
  return i + 1 | 0;
}

function use(t) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var o = TiliaCore._connect(t, (function () {
          setCount(_inc);
        }));
  React.useEffect(function () {
        TiliaCore._flush(o);
        return (function () {
                  TiliaCore._clear(o);
                });
      });
  return t[1];
}

var make = TiliaCore.make;

export {
  make ,
  _inc ,
  use ,
}
/* react Not a pure module */
