// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as TiliaQuerySchema from "./TiliaQuerySchema.mjs";

function observedKeys(results) {
  return Tilia._canopy(results).live;
}

function getResult(results, entry) {
  let result = results[entry.key];
  if (result == null) {
    return "loading";
  } else {
    return result;
  }
}

function makeFind(schema, source, loaded, results, reportError) {
  return entry => {
    if (entry.state === "LiveRemote") {
      return;
    }
    entry.close();
    let active = {
      contents: true
    };
    let cleanup = {
      contents: () => {}
    };
    let close = () => {
      if (!active.contents) {
        return;
      }
      active.contents = false;
      let clean = cleanup.contents;
      cleanup.contents = () => {};
      clean();
    };
    entry.close = close;
    let accept = (claim, state, values) => {
      if (!active.contents) {
        return;
      }
      let match = getResult(results, entry);
      let weaker;
      weaker = typeof match !== "object" || match.state !== "loaded" ? false : TiliaQuerySchema.rank(claim) < TiliaQuerySchema.rank(match.claim);
      if (!weaker) {
        entry.state = state;
        return loaded(entry, values, claim);
      }
    };
    if (source.online.value) {
      entry.fetchedAt = schema.now();
    }
    source.find(entry.query, {
      partial: values => accept("partial", "LoadedPartial", values),
      local: values => accept("local", "LoadedLocal", values),
      fresh: values => accept("fresh", "LoadedRemote", values),
      live: values => accept("fresh", "LiveRemote", values),
      fail: message => {
        if (!active.contents) {
          return;
        }
        let match = TiliaQuerySchema.project(source.online.value, getResult(results, entry));
        if (typeof match === "object" && match.state === "loaded") {
          return reportError(entry.query, message);
        }
        results[entry.key] = {
          state: "noData",
          reason: {
            reason: "failed",
            message: message
          }
        };
      },
      end: () => {
        if (active.contents) {
          if (entry.state === "LiveRemote") {
            entry.state = "LoadedRemote";
          }
          entry.fetchedAt = 0.0;
          return close();
        }
      },
      finally: fn => {
        if (active.contents) {
          cleanup.contents = fn;
          return;
        } else {
          return fn();
        }
      }
    });
  };
}

function makeGetEntry(schema, fetch, entries, results) {
  return query => {
    let k = schema.key(query);
    let entry = entries[k];
    if (entry !== null && entry !== undefined) {
      return entry;
    }
    entry === null;
    let entry$1 = {
      key: k,
      query: query,
      lastSeen: schema.now(),
      refreshedAt: 0.0,
      fetchedAt: 0.0,
      state: "Pristine",
      close: () => {}
    };
    results[k] = "loading";
    entries[k] = entry$1;
    fetch(entry$1);
    return entry$1;
  };
}

function makeOne(getEntry, results, online) {
  return query => {
    let match = TiliaQuerySchema.project(online.value, getResult(results, getEntry(query)));
    if (typeof match !== "object") {
      return "loading";
    }
    if (match.state !== "loaded") {
      return {
        state: "noData",
        reason: match.reason
      };
    }
    let claim = match.claim;
    let value = match.data[0];
    if (value == null) {
      return {
        state: "noData",
        reason: {
          reason: "noMatch",
          claim: claim
        }
      };
    } else {
      return {
        state: "loaded",
        claim: claim,
        data: value
      };
    }
  };
}

function makeArray(getEntry, results, online) {
  return query => TiliaQuerySchema.project(online.value, getResult(results, getEntry(query)));
}

function make(param) {
  let schema = param.schema;
  let now = schema.now;
  let sort = schema.sort;
  let matches = schema.matches;
  let id = schema.id;
  let onError = param.onError;
  let expiry = param.expiry;
  let reportError = (query, message) => onError(query, message);
  let itemById = Tilia.tilia(TiliaQuerySchema.Dict.make());
  let idsByKey = Tilia.tilia(TiliaQuerySchema.Dict.make());
  let entries = TiliaQuerySchema.Dict.make();
  let results = Tilia.tilia(TiliaQuerySchema.Dict.make());
  let joinEntries = value => {
    let vid = id(value);
    let joined = {
      contents: false
    };
    TiliaQuerySchema.Dict.forEach(entries, entry => {
      if (matches(entry.query, value)) {
        joined.contents = true;
        let ids = idsByKey[entry.key];
        if ((ids == null) || ids.includes(vid)) {
          return;
        } else {
          idsByKey[entry.key] = ids.concat([vid]);
          return;
        }
      }
      let ids$1 = idsByKey[entry.key];
      if ((ids$1 == null) || !ids$1.includes(vid)) {
        return;
      } else {
        idsByKey[entry.key] = ids$1.filter(i => i !== vid);
        return;
      }
    });
    return joined.contents;
  };
  let binding_item = rid => {
    let value = itemById[rid];
    if (value == null) {
      return;
    } else {
      return Primitive_option.some(value);
    }
  };
  let binding_changed = values => {
    values.forEach(value => {
      let vid = id(value);
      itemById[vid] = value;
      if (!joinEntries(value)) {
        return TiliaQuerySchema.Dict.$$delete(itemById, vid);
      }
    });
  };
  let binding_removed = ids => {
    ids.forEach(rid => {
      TiliaQuerySchema.Dict.$$delete(itemById, rid);
      TiliaQuerySchema.Dict.forEachWithKey(idsByKey, (ids, key) => {
        if (ids.includes(rid)) {
          idsByKey[key] = ids.filter(i => i !== rid);
          return;
        }
      });
    });
  };
  let binding_place = value => {
    itemById[id(value)] = value;
    joinEntries(value);
  };
  let binding = {
    item: binding_item,
    changed: binding_changed,
    removed: binding_removed,
    place: binding_place
  };
  let match = param.connect(binding);
  let source = match[0];
  let loaded = (entry, values, claim) => {
    if (claim === "fresh") {
      entry.refreshedAt = now();
    }
    values.forEach(value => {
      itemById[id(value)] = value;
    });
    let ids = values.map(id);
    idsByKey[entry.key] = ids;
    let build = () => {
      let values = [];
      let ids = idsByKey[entry.key];
      if (ids == null) {
        ids === null;
      } else {
        ids.forEach(id => {
          let value = itemById[id];
          if (value == null) {
            return;
          }
          values.push(value);
        });
      }
      return sort(entry.query)(values);
    };
    results[entry.key] = {
      state: "loaded",
      claim: claim,
      data: Tilia.computed(build)
    };
  };
  let fetch = makeFind(schema, source, loaded, results, reportError);
  let getEntry = makeGetEntry(schema, entry => fetch(entry), entries, results);
  let clearOnline = Tilia.watch(() => source.online.value, online => {
    if (online) {
      return TiliaQuerySchema.Dict.forEach(entries, entry => fetch(entry));
    } else {
      return TiliaQuerySchema.Dict.forEach(entries, entry => {
        entry.fetchedAt = 0.0;
        let match = getResult(results, entry);
        if (typeof match === "object") {
          return;
        }
        results[entry.key] = {
          state: "noData",
          reason: "offline"
        };
      });
    }
  });
  let tick = () => {
    let t = now();
    let buffer = source.online.value ? expiry.refresh / 8.0 : 0.0;
    let freshLimit = t - expiry.refresh - buffer;
    let live = Tilia._canopy(results).live;
    let online = source.online.value;
    let dropped = [];
    TiliaQuerySchema.Dict.forEach(entries, entry => {
      if (live.has(entry.key)) {
        entry.lastSeen = t;
      }
      if (t > entry.lastSeen + expiry.memory) {
        dropped.push(entry);
        return;
      }
      let match = entry.state;
      let match$1 = getResult(results, entry);
      let stale;
      switch (match) {
        case "Pristine" :
          stale = typeof match$1 === "object";
          break;
        case "LiveRemote" :
          stale = false;
          break;
        default:
          stale = true;
      }
      if (stale && online && entry.refreshedAt < t - expiry.refresh && entry.fetchedAt < t - expiry.refresh && t < entry.lastSeen + expiry.refresh) {
        fetch(entry);
      }
      if (entry.state !== "LoadedRemote") {
        return;
      }
      let match$2 = getResult(results, entry);
      if (typeof match$2 !== "object") {
        return;
      }
      if (match$2.state !== "loaded") {
        return;
      }
      switch (match$2.claim) {
        case "partial" :
        case "local" :
          return;
        case "fresh" :
          if (entry.refreshedAt < freshLimit) {
            results[entry.key] = {
              state: "loaded",
              claim: "local",
              data: match$2.data
            };
            return;
          } else {
            return;
          }
      }
    });
    if (dropped.length === 0) {
      return;
    }
    let orphans = new Set();
    dropped.forEach(entry => {
      entry.close();
      source.forget(entry.query);
      let key = entry.key;
      let ids = idsByKey[key];
      if (ids == null) {
        ids === null;
      } else {
        ids.forEach(id => {
          orphans.add(id);
        });
      }
      TiliaQuerySchema.Dict.$$delete(entries, key);
      TiliaQuerySchema.Dict.$$delete(results, key);
      TiliaQuerySchema.Dict.$$delete(idsByKey, key);
    });
    TiliaQuerySchema.Dict.forEach(idsByKey, ids => {
      ids.forEach(id => {
        orphans.delete(id);
      });
    });
    orphans.forEach(id => TiliaQuerySchema.Dict.$$delete(itemById, id));
  };
  return [
    {
      one: makeOne(getEntry, results, source.online),
      array: makeArray(getEntry, results, source.online),
      tick: tick,
      dispose: () => {
        clearOnline();
        TiliaQuerySchema.Dict.forEach(entries, entry => entry.close());
      },
      _canopy: () => {
        let match = Tilia._canopy(results);
        return {
          live: Array.from(match.live),
          idle: Array.from(match.idle)
        };
      }
    },
    match[1]
  ];
}

export {
  observedKeys,
  getResult,
  makeFind,
  makeGetEntry,
  makeOne,
  makeArray,
  make,
}
/* Tilia Not a pure module */
