// Generated by ReScript, PLEASE EDIT WITH CARE


let Channel = {};

let make = (() => ({}));

function $$delete(d, k) {
  Reflect.deleteProperty(d, k);
}

function forEach(d, fn) {
  Object.values(d).forEach(fn);
}

function forEachWithKey(d, fn) {
  Object.entries(d).forEach(param => fn(param[1], param[0]));
}

let Dict = {
  make: make,
  $$delete: $$delete,
  forEach: forEach,
  forEachWithKey: forEachWithKey
};

let Arr = {};

function rank(claim) {
  switch (claim) {
    case "partial" :
      return 0;
    case "local" :
      return 1;
    case "fresh" :
      return 2;
  }
}

function project(online, result) {
  if (typeof result !== "object") {
    return result;
  }
  if (result.state !== "loaded") {
    return result;
  }
  switch (result.claim) {
    case "partial" :
      if (result.data.length === 0) {
        if (online) {
          return "loading";
        } else {
          return {
            state: "noData",
            reason: "offline"
          };
        }
      } else {
        return result;
      }
    case "local" :
    case "fresh" :
      return result;
  }
}

let sortedStringify = (function sortedStringify(value) {
  return JSON.stringify(value, function(_key, value) {
    if (value && typeof value === "object" && !Array.isArray(value)) {
      const sorted = {};
      for (const key of Object.keys(value).sort()) {
        sorted[key] = value[key];
      }
      return sorted;
    }
    return value;
  });
});

export {
  Channel,
  Dict,
  Arr,
  rank,
  project,
  sortedStringify,
}
/* No side effect */
