// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as TiliaQuerySchema from "./TiliaQuerySchema.mjs";

let rowTag = "row";

function make() {
  let tags = TiliaQuerySchema.Dict.make();
  let tagged = tag => {
    let entries = tags[tag];
    if (entries !== null && entries !== undefined) {
      return entries;
    }
    entries === null;
    let entries$1 = TiliaQuerySchema.Dict.make();
    tags[tag] = entries$1;
    return entries$1;
  };
  return {
    get: (tag, keys, set) => {
      let entries = tagged(tag);
      set(keys !== undefined ? Stdlib_Array.filterMap(keys, key => {
          let value = entries[key];
          if (value == null) {
            return;
          } else {
            return value;
          }
        }) : Object.values(entries));
    },
    keys: (tag, set) => set(Object.keys(tagged(tag))),
    set: (tag, key, value) => {
      if (value !== undefined) {
        tagged(tag)[key] = value;
        return;
      } else {
        return TiliaQuerySchema.Dict.$$delete(tagged(tag), key);
      }
    }
  };
}

let Kv = {
  make: make
};

let encodeOp = (function encodeOp(entry) {
  return JSON.stringify({seq: entry.seq, op: entry.op, change: entry.change});
});

let parseOp = (function parseOp(value) {
  try {
    const r = JSON.parse(value);
    if (
      r &&
      typeof r.seq === "number" &&
      r.op &&
      (r.op.op === "upsert" || r.op.op === "remove") &&
      (r.change ? typeof r.change.change === "string" : r.op.op === "remove")
    ) {
      return {seq: r.seq, op: r.op, change: r.change, flight: false};
    }
  } catch (_) {}
  return undefined;
});

let snapshot = (function snapshot(value) {
  return JSON.parse(JSON.stringify(value));
});

let parseRow = (function parseRow(value) {
  try {
    const r = JSON.parse(value);
    if (r && typeof r === "object") return r;
  } catch (_) {}
  return undefined;
});

let parseRecord = (function parseRecord(value) {
  try {
    const r = JSON.parse(value);
    if (r && typeof r.key === "string" && Array.isArray(r.ids) && typeof r.lastSeen === "number") {
      return r;
    }
  } catch (_) {}
  return undefined;
});

function connect(param, binding) {
  let schema = param.schema;
  let now = schema.now;
  let key = schema.key;
  let matches = schema.matches;
  let id = schema.id;
  let merge = param.merge;
  let lookup = param.lookup;
  let persist = param.persist;
  let remote = param.remote;
  let expiry = param.expiry;
  let putRow = value => persist.set(rowTag, id(value), JSON.stringify(value));
  let dropRow = rid => persist.set(rowTag, rid, undefined);
  let decodeRows = values => Stdlib_Array.filterMap(values, value => {
    let row = parseRow(value);
    if (row == null) {
      return;
    } else {
      return Primitive_option.some(row);
    }
  });
  let queryTag = "query";
  let syntheticPrefix = "__id:";
  let registry = TiliaQuerySchema.Dict.make();
  let persistRecord = record => persist.set(queryTag, record.key, JSON.stringify(record));
  let held = TiliaQuerySchema.Dict.make();
  let lastFindAt = TiliaQuerySchema.Dict.make();
  let recorded = TiliaQuerySchema.Dict.make();
  let findAt = k => {
    let t = lastFindAt[k];
    if (t == null) {
      if (t === null) {
        return 0.0;
      } else {
        return 0.0;
      }
    } else {
      return t;
    }
  };
  let recordSeen = (k, query, claim, ids) => {
    let current = recorded[k];
    let weaker;
    weaker = (current == null) ? false : TiliaQuerySchema.rank(claim) < TiliaQuerySchema.rank(current);
    if (weaker) {
      return;
    }
    recorded[k] = claim;
    let record = registry[k];
    let record$1;
    let exit = 0;
    if (record == null) {
      exit = 1;
    } else {
      record$1 = record;
    }
    if (exit === 1) {
      let record$2 = {
        key: k,
        query: query,
        ids: [],
        lastSeen: 0.0
      };
      registry[k] = record$2;
      record$1 = record$2;
    }
    record$1.lastSeen = Math.max(record$1.lastSeen, findAt(k));
    record$1.ids = ids;
    persistRecord(record$1);
  };
  let joinRegistry = value => {
    let vid = id(value);
    TiliaQuerySchema.Dict.forEachWithKey(held, (query, k) => {
      let record = registry[k];
      if (record == null) {
        return;
      } else if (matches(query, value)) {
        if (!record.ids.includes(vid)) {
          record.ids = record.ids.concat([vid]);
          return persistRecord(record);
        } else {
          return;
        }
      } else if (record.ids.includes(vid)) {
        record.ids = record.ids.filter(i => i !== vid);
        return persistRecord(record);
      } else {
        return;
      }
    });
    let listed = {
      contents: false
    };
    TiliaQuerySchema.Dict.forEach(registry, record => {
      if (record.ids.includes(vid)) {
        listed.contents = true;
        return;
      }
    });
    return listed.contents;
  };
  let match = Tilia.signal(0);
  let setPending = match[1];
  let status = Tilia.tilia({
    pending: Tilia.lift(match[0]),
    rejected: []
  });
  let outboxTag = "outbox";
  let outbox = [];
  let nextSeq = {
    contents: 0.0
  };
  let opId = op => {
    if (op.op === "upsert") {
      return id(op.value);
    } else {
      return op.id;
    }
  };
  let rejectionId = rejection => {
    switch (rejection.rejection) {
      case "createConflict" :
      case "createFailed" :
        return id(rejection.edited);
      case "updateConflict" :
      case "updateFailed" :
        return id(rejection.edited);
      case "removeConflict" :
      case "removeFailed" :
        return id(rejection.base);
    }
  };
  let rejectionSeq = TiliaQuerySchema.Dict.make();
  let seqOf = rejection => {
    let seq = rejectionSeq[rejectionId(rejection)];
    if (seq == null) {
      if (seq === null) {
        return 0.0;
      } else {
        return 0.0;
      }
    } else {
      return seq;
    }
  };
  let addRejection = (seq, rejection) => {
    let rid = rejectionId(rejection);
    let rejection$1 = snapshot(rejection);
    let i = status.rejected.findIndex(value => rejectionId(value) === rid);
    if (i !== -1) {
      status.rejected[i] = rejection$1;
      return;
    }
    rejectionSeq[rid] = seq;
    let i$1 = status.rejected.findIndex(value => seqOf(value) > seq);
    if (i$1 !== -1) {
      status.rejected.splice(i$1, 0, rejection$1);
    } else {
      status.rejected.push(rejection$1);
    }
  };
  let dropRejection = rid => {
    let i = status.rejected.findIndex(value => rejectionId(value) === rid);
    if (i !== -1) {
      status.rejected.splice(i, 1);
      TiliaQuerySchema.Dict.$$delete(rejectionSeq, rid);
      return true;
    } else {
      return false;
    }
  };
  let persistOp = entry => persist.set(outboxTag, entry.seq.toString(), encodeOp(entry));
  let confirmed = entry => {
    let i = outbox.indexOf(entry);
    if (i >= 0) {
      outbox.splice(i, 1);
    }
    persist.set(outboxTag, entry.seq.toString(), undefined);
    setPending(outbox.length);
  };
  let pending = rid => outbox.find(entry => opId(entry.op) === rid);
  let applyPending = (query, values) => {
    return outbox.reduce((values, param) => {
      let op = param.op;
      if (op.op === "upsert") {
        let value = op.value;
        let vid = id(value);
        if (matches(query, value)) {
          if (values.some(v => id(v) === vid)) {
            return values.map(v => {
              if (id(v) === vid) {
                return value;
              } else {
                return v;
              }
            });
          } else {
            return values.concat([value]);
          }
        } else {
          return values.filter(v => id(v) !== vid);
        }
      }
      let rid = op.id;
      return values.filter(v => id(v) !== rid);
    }, values);
  };
  let forget = rid => {
    binding.removed([rid]);
    TiliaQuerySchema.Dict.forEach(registry, record => {
      if (record.ids.includes(rid)) {
        record.ids = record.ids.filter(i => i !== rid);
        return persistRecord(record);
      }
    });
    dropRow(rid);
  };
  let place = value => {
    binding.place(value);
    joinRegistry(value);
    putRow(value);
  };
  let conflict = change => {
    switch (change.change) {
      case "clean" :
        throw {
          RE_EXN_ID: "Invalid_argument",
          _1: "clean values cannot conflict",
          Error: new Error()
        };
      case "created" :
        return {
          rejection: "createConflict",
          edited: change.edited
        };
      case "updated" :
        return {
          rejection: "updateConflict",
          base: change.base,
          edited: change.edited
        };
      case "removed" :
        return {
          rejection: "removeConflict",
          base: change.base
        };
    }
  };
  let failed = (change, message) => {
    switch (change.change) {
      case "clean" :
        throw {
          RE_EXN_ID: "Invalid_argument",
          _1: "clean values cannot fail",
          Error: new Error()
        };
      case "created" :
        return {
          rejection: "createFailed",
          edited: change.edited,
          message: message
        };
      case "updated" :
        return {
          rejection: "updateFailed",
          base: change.base,
          edited: change.edited,
          message: message
        };
      case "removed" :
        return {
          rejection: "removeFailed",
          base: change.base,
          message: message
        };
    }
  };
  let merged = (change, remoteValue) => {
    if (merge === undefined) {
      return false;
    }
    let accepted = {
      contents: false
    };
    Tilia.batch(() => {
      accepted.contents = merge(change, remoteValue);
    });
    return accepted.contents;
  };
  let reconcile = remoteValue => {
    let rid = id(remoteValue);
    let entry = pending(rid);
    if (entry !== undefined) {
      let change = entry.change;
      if (change !== undefined) {
        if (merged(change, remoteValue)) {
          let match;
          switch (change.change) {
            case "clean" :
              let value = change.value;
              match = [
                {
                  change: "clean",
                  value: value
                },
                value
              ];
              break;
            case "created" :
              let edited = change.edited;
              match = [
                {
                  change: "updated",
                  base: remoteValue,
                  edited: edited
                },
                edited
              ];
              break;
            case "updated" :
              let edited$1 = change.edited;
              match = [
                {
                  change: "updated",
                  base: remoteValue,
                  edited: edited$1
                },
                edited$1
              ];
              break;
            case "removed" :
              let base = change.base;
              match = [
                {
                  change: "removed",
                  base: base
                },
                base
              ];
              break;
          }
          let next = match[0];
          entry.change = next;
          if (next.change === "updated") {
            entry.op = {
              op: "upsert",
              value: next.edited
            };
          }
          persistOp(entry);
          return match[1];
        }
        confirmed(entry);
        addRejection(entry.seq, conflict(change));
        return remoteValue;
      }
      confirmed(entry);
      return remoteValue;
    }
    let current = binding.item(rid);
    if (current === undefined) {
      return remoteValue;
    }
    let current$1 = Primitive_option.valFromOption(current);
    if (merged({
        change: "clean",
        value: current$1
      }, remoteValue)) {
      return current$1;
    } else {
      return remoteValue;
    }
  };
  let pushPending = () => {
    if (!remote.online.value) {
      return;
    }
    let batch = outbox.filter(entry => !entry.flight);
    if (batch.length === 0) {
      return;
    }
    batch.forEach(entry => {
      entry.flight = true;
    });
    let settled = {
      contents: false
    };
    let answered = [];
    let waiting = entry => {
      if (outbox.includes(entry)) {
        return !answered.includes(entry);
      } else {
        return false;
      }
    };
    let findUpsert = vid => batch.find(entry => {
      if (!waiting(entry)) {
        return false;
      }
      let match = entry.op;
      if (match.op === "upsert") {
        return id(match.value) === vid;
      } else {
        return false;
      }
    });
    let findRemove = rid => batch.find(entry => {
      if (!waiting(entry)) {
        return false;
      }
      let match = entry.op;
      if (match.op === "upsert") {
        return false;
      } else {
        return match.id === rid;
      }
    });
    let findAny = rid => batch.find(entry => {
      if (waiting(entry)) {
        return opId(entry.op) === rid;
      } else {
        return false;
      }
    });
    let revert = (entry, message) => {
      let change = entry.change;
      confirmed(entry);
      if (change !== undefined) {
        switch (change.change) {
          case "clean" :
            break;
          case "created" :
            forget(id(change.edited));
            break;
          case "updated" :
          case "removed" :
            place(change.base);
            break;
        }
      }
      if (change !== undefined) {
        return addRejection(entry.seq, failed(change, message));
      }
    };
    remote.push(batch.map(entry => entry.op), {
      set: value => {
        if (settled.contents) {
          return;
        }
        let entry = findUpsert(id(value));
        if (entry !== undefined) {
          answered.push(entry);
          confirmed(entry);
          return place(value);
        }
      },
      removed: rid => {
        if (settled.contents) {
          return;
        }
        let entry = findRemove(rid);
        if (entry !== undefined) {
          answered.push(entry);
          return confirmed(entry);
        }
      },
      conflict: value => {
        if (settled.contents) {
          return;
        }
        let entry = findAny(id(value));
        if (entry === undefined) {
          return;
        }
        answered.push(entry);
        let change = entry.change;
        if (change !== undefined) {
          if (merged(change, value)) {
            let match;
            switch (change.change) {
              case "clean" :
                let value$1 = change.value;
                match = [
                  {
                    change: "clean",
                    value: value$1
                  },
                  value$1
                ];
                break;
              case "created" :
                let edited = change.edited;
                match = [
                  {
                    change: "updated",
                    base: value,
                    edited: edited
                  },
                  edited
                ];
                break;
              case "updated" :
                let edited$1 = change.edited;
                match = [
                  {
                    change: "updated",
                    base: value,
                    edited: edited$1
                  },
                  edited$1
                ];
                break;
              case "removed" :
                let base = change.base;
                match = [
                  {
                    change: "removed",
                    base: base
                  },
                  base
                ];
                break;
            }
            let next = match[0];
            entry.change = next;
            if (next.change === "updated") {
              entry.op = {
                op: "upsert",
                value: next.edited
              };
            }
            persistOp(entry);
            entry.flight = false;
            return place(match[1]);
          }
          confirmed(entry);
          addRejection(entry.seq, conflict(change));
          return place(value);
        }
        confirmed(entry);
        place(value);
      },
      reject: (rid, message) => {
        if (settled.contents) {
          return;
        }
        let entry = findAny(rid);
        if (entry !== undefined) {
          answered.push(entry);
          return Tilia.batch(() => revert(entry, message));
        }
      },
      retry: () => {
        if (!settled.contents) {
          settled.contents = true;
          batch.forEach(entry => {
            if (waiting(entry)) {
              entry.flight = false;
              return;
            }
          });
          return;
        }
      },
      fail: message => {
        if (!settled.contents) {
          settled.contents = true;
          return Tilia.batch(() => {
            batch.forEach(entry => {
              if (waiting(entry)) {
                return revert(entry, message);
              }
            });
          });
        }
      }
    });
  };
  let enqueue = (change, op) => {
    let current = pending(opId(op));
    let entry;
    if (current !== undefined) {
      let entry$1 = {
        seq: current.seq,
        op: op,
        change: change,
        flight: false
      };
      let i = outbox.indexOf(current);
      outbox.splice(i, 1, entry$1);
      entry = entry$1;
    } else {
      let seq = Math.max(now(), nextSeq.contents);
      nextSeq.contents = seq + 1.0;
      let entry$2 = {
        seq: seq,
        op: op,
        change: change,
        flight: false
      };
      outbox.push(entry$2);
      entry = entry$2;
    }
    persistOp(entry);
    setPending(outbox.length);
    pushPending();
  };
  let upsert = value => {
    let vid = id(value);
    dropRejection(vid);
    let match = pending(vid);
    let change;
    if (match !== undefined) {
      let match$1 = match.change;
      if (match$1 !== undefined) {
        switch (match$1.change) {
          case "clean" :
            change = {
              change: "updated",
              base: match$1.value,
              edited: value
            };
            break;
          case "created" :
            change = {
              change: "created",
              edited: value
            };
            break;
          case "updated" :
          case "removed" :
            change = {
              change: "updated",
              base: match$1.base,
              edited: value
            };
            break;
        }
      } else {
        change = {
          change: "created",
          edited: value
        };
      }
    } else {
      let base = binding.item(vid);
      change = base !== undefined ? ({
          change: "updated",
          base: Primitive_option.valFromOption(base),
          edited: value
        }) : ({
          change: "created",
          edited: value
        });
    }
    binding.place(value);
    if (!joinRegistry(value)) {
      let record = {
        key: syntheticPrefix + vid,
        query: undefined,
        ids: [vid],
        lastSeen: now()
      };
      registry[record.key] = record;
      persistRecord(record);
    }
    putRow(value);
    enqueue(change, {
      op: "upsert",
      value: value
    });
  };
  let remove = rid => {
    dropRejection(rid);
    let entry = pending(rid);
    if (entry !== undefined) {
      let match = entry.change;
      let base;
      if (match !== undefined) {
        switch (match.change) {
          case "clean" :
            base = match.value;
            break;
          case "created" :
            if (entry.flight) {
              forget(rid);
              return enqueue(undefined, {
                op: "remove",
                id: rid
              });
            } else {
              confirmed(entry);
              return forget(rid);
            }
          case "updated" :
            base = match.base;
            break;
          case "removed" :
            return;
        }
      } else {
        forget(rid);
        return enqueue(undefined, {
          op: "remove",
          id: rid
        });
      }
      forget(rid);
      return enqueue({
        change: "removed",
        base: base
      }, {
        op: "remove",
        id: rid
      });
    }
    let base$1 = binding.item(rid);
    let change = base$1 !== undefined ? ({
        change: "removed",
        base: Primitive_option.valFromOption(base$1)
      }) : undefined;
    forget(rid);
    enqueue(change, {
      op: "remove",
      id: rid
    });
  };
  let receiveChanged = values => {
    values.forEach(value => {
      let value$1 = reconcile(value);
      let vid = id(value$1);
      let match = pending(vid);
      if (match !== undefined) {
        let match$1 = match.op;
        if (match$1.op !== "upsert") {
          return forget(vid);
        }
      }
      binding.changed([value$1]);
      if (joinRegistry(value$1)) {
        return putRow(value$1);
      }
    });
  };
  let receiveRemoved = ids => Tilia.batch(() => {
    ids.forEach(rid => {
      let entry = pending(rid);
      if (entry !== undefined) {
        let change = entry.change;
        confirmed(entry);
        if (change !== undefined) {
          switch (change.change) {
            case "created" :
              addRejection(entry.seq, {
                rejection: "createConflict",
                edited: change.edited
              });
              break;
            case "updated" :
              addRejection(entry.seq, {
                rejection: "updateConflict",
                base: change.base,
                edited: change.edited
              });
              break;
            case "clean" :
            case "removed" :
              break;
          }
        }
      }
      forget(rid);
    });
  });
  persist.get(outboxTag, undefined, values => {
    values.forEach(value => {
      let entry = parseOp(value);
      if (entry == null) {
        return;
      }
      outbox.push(entry);
      nextSeq.contents = Math.max(nextSeq.contents, entry.seq + 1.0);
    });
    outbox.sort((a, b) => a.seq - b.seq);
    setPending(outbox.length);
    pushPending();
  });
  let findQuery = (query, channel) => {
    let k = key(query);
    let t = now();
    held[k] = query;
    lastFindAt[k] = t;
    let record = registry[k];
    if (record == null) {
      record === null;
    } else {
      record.lastSeen = t;
      persistRecord(record);
    }
    let received = values => {
      let values$1 = applyPending(query, values.map(reconcile));
      values$1.forEach(putRow);
      recordSeen(k, query, "fresh", values$1.map(id));
      return values$1;
    };
    let answer = record => persist.get(rowTag, record.ids, values => {
      let rows = decodeRows(values);
      recordSeen(k, query, "local", rows.map(id));
      channel.local(rows);
    });
    let unregistered = () => {
      if (lookup !== undefined) {
        return lookup(query, {
          partial: values => channel.partial(values),
          local: values => {
            recordSeen(k, query, "local", values.map(id));
            channel.local(values);
          }
        });
      } else {
        return persist.get(rowTag, undefined, values => channel.partial(decodeRows(values).filter(row => matches(query, row))));
      }
    };
    let record$1 = registry[k];
    let exit = 0;
    if (record$1 == null) {
      exit = 1;
    } else {
      answer(record$1);
    }
    if (exit === 1) {
      persist.get(queryTag, [k], values => {
        let value = values[0];
        if (value == null) {
          return unregistered();
        }
        let record = parseRecord(value);
        if (record == null) {
          return unregistered();
        }
        registry[k] = record;
        answer(record);
      });
    }
    if (remote.online.value) {
      return remote.fetch(query, {
        fresh: values => channel.fresh(received(values)),
        live: values => channel.live(received(values)),
        fail: channel.fail,
        end: channel.end,
        finally: channel.finally
      });
    }
  };
  let forgetQuery = query => {
    let k = key(query);
    TiliaQuerySchema.Dict.$$delete(held, k);
    TiliaQuerySchema.Dict.$$delete(lastFindAt, k);
    TiliaQuerySchema.Dict.$$delete(recorded, k);
  };
  let clearOnlineStore = Tilia.watch(() => remote.online.value, online => {
    if (online) {
      return pushPending();
    }
  });
  let take = rejection => {
    let i = status.rejected.indexOf(rejection);
    if (i !== -1) {
      status.rejected.splice(i, 1);
      TiliaQuerySchema.Dict.$$delete(rejectionSeq, rejectionId(rejection));
      return true;
    } else {
      return false;
    }
  };
  let discard = rejection => {
    take(rejection);
  };
  let retry = rejection => {
    if (!take(rejection)) {
      return;
    }
    switch (rejection.rejection) {
      case "createConflict" :
      case "createFailed" :
        return upsert(snapshot(rejection.edited));
      case "updateConflict" :
      case "updateFailed" :
        return upsert(snapshot(rejection.edited));
      case "removeConflict" :
      case "removeFailed" :
        return remove(id(rejection.base));
    }
  };
  let lastPurgeAt = {
    contents: Number.NEGATIVE_INFINITY
  };
  return [
    {
      online: remote.online,
      find: findQuery,
      forget: forgetQuery,
      tick: () => {
        let t = now();
        pushPending();
        if (t > lastPurgeAt.contents + expiry.local / 8.0) {
          lastPurgeAt.contents = t;
          return persist.get(queryTag, undefined, values => {
            values.forEach(value => {
              let record = parseRecord(value);
              if (record == null) {
                return;
              }
              let match = registry[record.key];
              if (match !== null && match !== undefined) {
                return;
              }
              if (match === null) {
                registry[record.key] = record;
                return;
              }
              registry[record.key] = record;
            });
            Object.keys(registry).filter(rkey => rkey.startsWith(syntheticPrefix)).forEach(rkey => {
              let rid = rkey.slice(syntheticPrefix.length);
              let value = binding.item(rid);
              if (value === undefined) {
                return;
              }
              let value$1 = Primitive_option.valFromOption(value);
              let adopted = {
                contents: false
              };
              TiliaQuerySchema.Dict.forEach(registry, record => {
                let query = record.query;
                if ((query == null) || !matches(query, value$1)) {
                  return;
                } else {
                  if (!record.ids.includes(rid)) {
                    record.ids = record.ids.concat([rid]);
                    persistRecord(record);
                  }
                  adopted.contents = true;
                  return;
                }
              });
              if (adopted.contents) {
                TiliaQuerySchema.Dict.$$delete(registry, rkey);
                return persist.set(queryTag, rkey, undefined);
              }
            });
            TiliaQuerySchema.Dict.forEach(registry, record => {
              let match = held[record.key];
              if (match == null) {
                match === null;
              } else {
                record.lastSeen = t;
                return persistRecord(record);
              }
              if (t > record.lastSeen + expiry.local) {
                TiliaQuerySchema.Dict.$$delete(registry, record.key);
                return persist.set(queryTag, record.key, undefined);
              }
            });
            persist.keys(rowTag, allIds => {
              let marked = new Set();
              TiliaQuerySchema.Dict.forEach(registry, record => {
                record.ids.forEach(id => {
                  marked.add(id);
                });
              });
              outbox.forEach(entry => {
                marked.add(opId(entry.op));
              });
              allIds.forEach(id => {
                if (!marked.has(id)) {
                  return dropRow(id);
                }
              });
            });
          });
        }
      },
      dispose: () => clearOnlineStore()
    },
    {
      upsert: upsert,
      remove: remove,
      receive: {
        changed: receiveChanged,
        removed: receiveRemoved
      },
      status: status,
      retry: retry,
      discard: discard
    }
  ];
}

export {
  rowTag,
  Kv,
  encodeOp,
  parseOp,
  snapshot,
  parseRow,
  parseRecord,
  connect,
}
/* Tilia Not a pure module */
