// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

let Channel = {};

let make = (() => ({}));

let $$Object = {};

let sortedStringify = (function sortedStringify(value) {
  return JSON.stringify(value, function(_key, value) {
    if (value && typeof value === "object" && !Array.isArray(value)) {
      const sorted = {};
      for (const key of Object.keys(value).sort()) {
        sorted[key] = value[key];
      }
      return sorted;
    }
    return value;
  });
});

let Json = {
  sortedStringify: sortedStringify
};

function emitter(run) {
  return self => (value => {
    let match = self.state;
    if (match === "Live") {
      return run(value);
    }
  });
}

function makeChannel(emit, fail) {
  let match = Tilia.signal("Live");
  let setState = match[1];
  let state = match[0];
  let channel = Tilia.carve(param => {
    let derived = param.derived;
    return {
      state: Tilia.lift(state),
      emit: derived(emitter(emit)),
      fail: derived(emitter(fail))
    };
  });
  return [
    channel,
    () => setState("Cancelled")
  ];
}

function make$1(id, remote, resolve) {
  let entries = make();
  let hold = () => {
    let released = {
      contents: false
    };
    let run = {
      contents: () => {}
    };
    let stopper = () => {
      if (!released.contents) {
        released.contents = true;
        return run.contents();
      }
    };
    let wire = done => {
      run.contents = done;
      if (released.contents) {
        return done();
      }
    };
    return [
      stopper,
      wire
    ];
  };
  let stop = entry => {
    entry.stopper();
    entry.active = false;
  };
  let remove = (itemId, entry) => {
    let current = Reflect.get(entries, itemId);
    if ((current == null) || !Primitive_object.equal(current, entry)) {
      return false;
    } else {
      stop(current);
      Reflect.deleteProperty(entries, itemId);
      return true;
    }
  };
  let cancel = () => {
    Object.keys(entries).forEach(itemId => {
      let entry = Reflect.get(entries, itemId);
      if ((entry == null) || !entry.active) {
        return;
      } else {
        return stop(entry);
      }
    });
  };
  let replay = () => {
    if (remote.online) {
      Object.keys(entries).forEach(itemId => {
        let entry = Reflect.get(entries, itemId);
        if ((entry == null) || entry.active) {
          return;
        } else {
          let onEmit = value => {
            if (remove(itemId, entry)) {
              resolve(value);
              return;
            }
          };
          let onFail = issue => {
            if (!remove(itemId, entry)) {
              return;
            }
            if (typeof issue !== "object") {
              return;
            }
            if (issue.TAG !== "Conflict") {
              return;
            }
            resolve(issue._0);
          };
          let match = makeChannel(onEmit, onFail);
          let cancelChannel = match[1];
          entry.active = true;
          let done = remote.upsert(entry.value, match[0]);
          let done$1 = done !== undefined ? done : () => {};
          entry.wire(() => {
            cancelChannel();
            done$1();
          });
          let current = Reflect.get(entries, itemId);
          if ((current == null) || !(Primitive_object.equal(current, entry) && current.active)) {
            return entry.stopper();
          } else {
            return;
          }
        }
      });
      return;
    }
  };
  let send = value => {
    let next = resolve(value);
    let itemId = id(next);
    let entry = Reflect.get(entries, itemId);
    if (entry == null) {
      entry === null;
    } else {
      stop(entry);
    }
    let match = hold();
    let entry$1 = {
      value: next,
      active: false,
      stopper: match[0],
      wire: match[1]
    };
    Reflect.set(entries, itemId, entry$1);
    if (remote.online) {
      replay();
    }
    return () => {
      remove(itemId, entry$1);
    };
  };
  return {
    send: send,
    replay: replay,
    cancel: cancel
  };
}

function make$2(fetch, upsert, resolve) {
  let replay = () => {
    fetch.replay();
    upsert.replay();
  };
  return {
    replay: replay,
    resolve: resolve
  };
}

function defaultNow() {
  return Date.now() / 1000.0;
}

function make$3(id, remote, staleOpt, gcOpt, nowOpt, keyOpt, invalidatesOpt, param) {
  let stale = staleOpt !== undefined ? staleOpt : 30.0;
  let gc = gcOpt !== undefined ? gcOpt : 300.0;
  let now = nowOpt !== undefined ? nowOpt : defaultNow;
  let key = keyOpt !== undefined ? keyOpt : sortedStringify;
  let invalidates = invalidatesOpt !== undefined ? invalidatesOpt : (param, param$1) => false;
  let cache = Tilia.tilia(make());
  let queries = Tilia.tilia(make());
  let meta = make();
  let staleKeys = Tilia.tilia(make());
  let fetchCancels = make();
  let stopFetch = cacheKey => {
    let cancel = Reflect.get(fetchCancels, cacheKey);
    if (cancel == null) {
      return;
    }
    cancel();
    Reflect.deleteProperty(fetchCancels, cacheKey);
  };
  let invalidate = item => {
    Object.keys(meta).forEach(cacheKey => {
      let m = Reflect.get(meta, cacheKey);
      if ((m == null) || !invalidates(m.filter, item)) {
        return;
      } else {
        Reflect.set(staleKeys, cacheKey, true);
        return;
      }
    });
  };
  let resolve = item => {
    Reflect.set(cache, id(item), item);
    invalidate(item);
    return item;
  };
  let loader = (cacheKey, filter) => ((_prev, set) => {
    let match = Reflect.get(staleKeys, cacheKey);
    if (match === undefined) {
      return;
    } else {
      stopFetch(cacheKey);
      let onEmit = list => {
        let ids = list.map(item => {
          let itemId = id(item);
          Reflect.set(cache, itemId, item);
          return itemId;
        });
        set({
          TAG: "Loaded",
          _0: ids
        });
        let m = Reflect.get(meta, cacheKey);
        if (m == null) {
          m === null;
        } else {
          m.fetched = now();
        }
        Reflect.deleteProperty(staleKeys, cacheKey);
      };
      let onFail = _message => {
        let m = Reflect.get(meta, cacheKey);
        if (m == null) {
          m === null;
        } else {
          m.fetched = now();
        }
        Reflect.deleteProperty(staleKeys, cacheKey);
      };
      let match$1 = makeChannel(onEmit, onFail);
      let cancelChannel = match$1[1];
      let cleanup = remote.fetch(filter, match$1[0]);
      let cleanup$1 = cleanup !== undefined ? cleanup : () => {};
      Reflect.set(fetchCancels, cacheKey, () => {
        cancelChannel();
        cleanup$1();
      });
      return;
    }
  });
  let fetch_replay = () => {
    let canopy = Tilia._canopy(queries);
    canopy.live.forEach(cacheKey => {
      Reflect.set(staleKeys, cacheKey, true);
    });
  };
  let fetch_resolve = (_filter, rows) => {
    rows.forEach(item => {
      Reflect.set(cache, id(item), item);
    });
  };
  let fetch = {
    replay: fetch_replay,
    resolve: fetch_resolve
  };
  let writes = make$1(id, remote, resolve);
  let syncer = make$2(fetch, writes, resolve);
  let online = {
    contents: remote.online
  };
  Tilia.watch(() => remote.online, live => {
    let prev = online.contents;
    online.contents = live;
    if (!prev && live) {
      return syncer.replay();
    } else if (prev && !live) {
      return writes.cancel();
    } else {
      return;
    }
  });
  let get = id => {
    let item = Reflect.get(cache, id);
    if (item == null) {
      return "NotFound";
    } else {
      return {
        TAG: "Loaded",
        _0: item
      };
    }
  };
  let query = filter => {
    let cacheKey = key(filter);
    let q = Reflect.get(queries, cacheKey);
    if (q !== null && q !== undefined) {
      return q;
    }
    q === null;
    Reflect.set(meta, cacheKey, {
      filter: filter,
      fetched: 0.0,
      idle: undefined
    });
    Reflect.set(staleKeys, cacheKey, true);
    let s = Tilia.source("Loading", loader(cacheKey, filter));
    Reflect.set(queries, cacheKey, s);
    return Reflect.get(queries, cacheKey);
  };
  let array = filter => {
    let ids = query(filter);
    if (typeof ids !== "object") {
      if (ids === "Loading") {
        return "Loading";
      } else {
        return "NotFound";
      }
    } else {
      return {
        TAG: "Loaded",
        _0: Tilia.tilia(ids._0.map(id => Tilia.computed(() => Reflect.get(cache, id))))
      };
    }
  };
  let dict = filter => {
    let ids = query(filter);
    if (typeof ids !== "object") {
      if (ids === "Loading") {
        return "Loading";
      } else {
        return "NotFound";
      }
    } else {
      return {
        TAG: "Loaded",
        _0: Tilia.tilia(Object.fromEntries(ids._0.map(id => [
          id,
          Tilia.computed(() => Reflect.get(cache, id))
        ])))
      };
    }
  };
  let sync = item => {
    syncer.resolve(item);
  };
  let upsert = item => writes.send(item);
  let tick = () => {
    let current = now();
    let canopy = Tilia._canopy(queries);
    canopy.live.forEach(k => {
      let m = Reflect.get(meta, k);
      if (m == null) {
        return;
      }
      m.idle = undefined;
      if (current - m.fetched >= stale) {
        Reflect.set(staleKeys, k, true);
        return;
      }
    });
    let evicted = {
      contents: false
    };
    canopy.idle.forEach(k => {
      let m = Reflect.get(meta, k);
      if (m == null) {
        return;
      }
      let t = m.idle;
      if (t !== undefined) {
        if (current - t >= gc) {
          stopFetch(k);
          Reflect.deleteProperty(queries, k);
          Reflect.deleteProperty(meta, k);
          Reflect.deleteProperty(staleKeys, k);
          evicted.contents = true;
          return;
        } else {
          return;
        }
      } else {
        m.idle = current;
        return;
      }
    });
    if (!evicted.contents) {
      return;
    }
    let referenced = new Set();
    Object.keys(queries).forEach(k => {
      let ids = Reflect.get(queries, k);
      if (typeof ids !== "object") {
        return;
      }
      ids._0.forEach(id => {
        referenced.add(id);
      });
    });
    Object.keys(cache).forEach(id => {
      if (!referenced.has(id)) {
        Reflect.deleteProperty(cache, id);
        return;
      }
    });
  };
  return {
    get: get,
    array: array,
    dict: dict,
    upsert: upsert,
    sync: sync,
    tick: tick
  };
}

export {
  Channel,
  $$Object,
  Json,
  make$3 as make,
}
/* Tilia Not a pure module */
