// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";

let Channel = {};

let make = (() => ({}));

let $$Object = {};

let sortedStringify = (function sortedStringify(value) {
  return JSON.stringify(value, function(_key, value) {
    if (value && typeof value === "object" && !Array.isArray(value)) {
      const sorted = {};
      for (const key of Object.keys(value).sort()) {
        sorted[key] = value[key];
      }
      return sorted;
    }
    return value;
  });
});

let Json = {
  sortedStringify: sortedStringify
};

function emitter(run) {
  return self => (value => {
    let match = self.state;
    if (match === "Live") {
      return run(value);
    }
  });
}

function makeChannel(emit, fail) {
  let match = Tilia.signal("Live");
  let setState = match[1];
  let state = match[0];
  let channel = Tilia.carve(param => {
    let derived = param.derived;
    return {
      state: Tilia.lift(state),
      emit: derived(emitter(emit)),
      fail: derived(emitter(fail))
    };
  });
  return [
    channel,
    () => setState("Cancelled")
  ];
}

function make$1(id, remote, local, resolve) {
  let entries = make();
  let pending = itemId => {
    let match = Reflect.get(entries, itemId);
    return match !== null && match !== undefined;
  };
  let stop = entry => {
    let cancel = entry.cancel;
    if (cancel !== undefined) {
      cancel();
      entry.cancel = undefined;
      return;
    }
  };
  let remove = (itemId, entry) => {
    let current = Reflect.get(entries, itemId);
    if ((current == null) || current !== entry) {
      return false;
    } else {
      stop(current);
      Reflect.deleteProperty(entries, itemId);
      return true;
    }
  };
  let cancel = () => {
    Object.keys(entries).forEach(itemId => {
      let entry = Reflect.get(entries, itemId);
      if (entry == null) {
        return;
      } else {
        return stop(entry);
      }
    });
  };
  let replay = () => {
    if (remote.online) {
      Object.keys(entries).forEach(itemId => {
        let entry = Reflect.get(entries, itemId);
        if (entry == null) {
          return;
        }
        let match = entry.cancel;
        if (match !== undefined) {
          return;
        } else {
          let settle = value => {
            if (remove(itemId, entry)) {
              local.save(value, false);
              resolve(value);
              return;
            }
          };
          let onFail = issue => {
            if (typeof issue === "object") {
              if (issue.TAG === "Conflict") {
                return settle(issue._0);
              } else if (remove(itemId, entry)) {
                return local.save(entry.value, false);
              } else {
                return;
              }
            }
            let current = Reflect.get(entries, itemId);
            if ((current == null) || current !== entry) {
              return;
            } else {
              return stop(current);
            }
          };
          let match$1 = makeChannel(settle, onFail);
          entry.cancel = match$1[1];
          return remote.upsert(entry.value, match$1[0]);
        }
      });
      return;
    }
  };
  let send = value => {
    let itemId = id(value);
    let entry = Reflect.get(entries, itemId);
    if (entry == null) {
      entry === null;
    } else {
      stop(entry);
    }
    Reflect.set(entries, itemId, {
      value: value,
      cancel: undefined
    });
    local.save(value, true);
    resolve(value);
    if (remote.online) {
      return replay();
    }
  };
  return {
    send: send,
    replay: replay,
    cancel: cancel,
    pending: pending
  };
}

function defaultNow() {
  return Date.now() / 1000.0;
}

function make$2(id, remote, local, staleOpt, gcOpt, nowOpt, keyOpt, invalidatesOpt, param) {
  let stale = staleOpt !== undefined ? staleOpt : 30.0;
  let gc = gcOpt !== undefined ? gcOpt : 300.0;
  let now = nowOpt !== undefined ? nowOpt : defaultNow;
  let key = keyOpt !== undefined ? keyOpt : sortedStringify;
  let invalidates = invalidatesOpt !== undefined ? invalidatesOpt : (param, param$1) => false;
  let local$1 = local !== undefined ? local : ({
      fetch: (param, param$1) => {},
      save: (param, param$1) => {},
      dirty: () => Promise.resolve([])
    });
  let cache = Tilia.tilia(make());
  let queries = Tilia.tilia(make());
  let arrays = Tilia.tilia(make());
  let dicts = Tilia.tilia(make());
  let meta = make();
  let staleKeys = Tilia.tilia(make());
  let fetchCancels = make();
  let stopFetch = cacheKey => {
    let cancel = Reflect.get(fetchCancels, cacheKey);
    if (cancel == null) {
      return;
    }
    cancel();
    Reflect.deleteProperty(fetchCancels, cacheKey);
  };
  let invalidate = item => {
    Object.keys(meta).forEach(cacheKey => {
      let m = Reflect.get(meta, cacheKey);
      if ((m == null) || !invalidates(m.filter, item)) {
        return;
      } else {
        Reflect.set(staleKeys, cacheKey, true);
        return;
      }
    });
  };
  let resolve = item => {
    Reflect.set(cache, id(item), item);
    invalidate(item);
    return item;
  };
  let writes = make$1(id, remote, local$1, resolve);
  let loader = (cacheKey, filter) => ((_prev, set) => {
    let match = Reflect.get(staleKeys, cacheKey);
    if (match === undefined) {
      return;
    } else {
      stopFetch(cacheKey);
      let fresh = () => {
        let m = Reflect.get(meta, cacheKey);
        if (m == null) {
          return;
        } else {
          m.fetched = now();
          return;
        }
      };
      let tier = (fetch, authority, fail) => {
        let match = makeChannel(rows => {
          let ids = rows.map(item => {
            let itemId = id(item);
            if (!writes.pending(itemId)) {
              Reflect.set(cache, itemId, item);
              if (authority) {
                local$1.save(item, false);
              }
            }
            return itemId;
          });
          set({
            TAG: "Loaded",
            _0: ids
          });
          if (authority) {
            return fresh();
          }
        }, fail);
        let cancelChannel = match[1];
        let cleanup = fetch(filter, match[0]);
        let cleanup$1 = cleanup !== undefined ? cleanup : () => {};
        return () => {
          cancelChannel();
          cleanup$1();
        };
      };
      let cancelLocal = tier(local$1.fetch, false, param => {});
      let cancelRemote = remote.online ? tier(remote.fetch, true, param => fresh()) : () => {};
      Reflect.set(fetchCancels, cacheKey, () => {
        cancelLocal();
        cancelRemote();
      });
      Reflect.deleteProperty(staleKeys, cacheKey);
      return;
    }
  });
  let replay = () => {
    let canopy = Tilia._canopy(queries);
    canopy.live.forEach(cacheKey => {
      Reflect.set(staleKeys, cacheKey, true);
    });
    writes.replay();
  };
  let online = {
    contents: remote.online
  };
  Tilia.watch(() => remote.online, live => {
    let prev = online.contents;
    online.contents = live;
    if (!prev && live) {
      return replay();
    } else if (prev && !live) {
      return writes.cancel();
    } else {
      return;
    }
  });
  let get = id => {
    let item = Reflect.get(cache, id);
    if (item == null) {
      return "NotFound";
    } else {
      return {
        TAG: "Loaded",
        _0: item
      };
    }
  };
  let query = filter => {
    let cacheKey = key(filter);
    let q = Reflect.get(queries, cacheKey);
    if (q !== null && q !== undefined) {
      return q;
    }
    q === null;
    Reflect.set(meta, cacheKey, {
      filter: filter,
      fetched: 0.0,
      idle: undefined
    });
    Reflect.set(staleKeys, cacheKey, true);
    let s = Tilia.source("Loading", loader(cacheKey, filter));
    Reflect.set(queries, cacheKey, s);
    return Reflect.get(queries, cacheKey);
  };
  let array = filter => {
    let cacheKey = key(filter);
    query(filter);
    let view = Reflect.get(arrays, cacheKey);
    if (view !== null && view !== undefined) {
      return view;
    }
    view === null;
    Reflect.set(arrays, cacheKey, Tilia.computed(() => {
      let ids = Reflect.get(queries, cacheKey);
      if (typeof ids !== "object") {
        if (ids === "Loading") {
          return "Loading";
        } else {
          return "NotFound";
        }
      } else {
        return {
          TAG: "Loaded",
          _0: Tilia.tilia(ids._0.map(id => Tilia.computed(() => Reflect.get(cache, id))))
        };
      }
    }));
    return Reflect.get(arrays, cacheKey);
  };
  let dict = filter => {
    let cacheKey = key(filter);
    query(filter);
    let view = Reflect.get(dicts, cacheKey);
    if (view !== null && view !== undefined) {
      return view;
    }
    view === null;
    Reflect.set(dicts, cacheKey, Tilia.computed(() => {
      let ids = Reflect.get(queries, cacheKey);
      if (typeof ids !== "object") {
        if (ids === "Loading") {
          return "Loading";
        } else {
          return "NotFound";
        }
      } else {
        return {
          TAG: "Loaded",
          _0: Tilia.tilia(Object.fromEntries(ids._0.map(id => [
            id,
            Tilia.computed(() => Reflect.get(cache, id))
          ])))
        };
      }
    }));
    return Reflect.get(dicts, cacheKey);
  };
  let sync = item => {
    resolve(item);
  };
  let upsert = item => writes.send(item);
  let tick = () => {
    let current = now();
    let canopy = Tilia._canopy(queries);
    canopy.live.forEach(k => {
      let m = Reflect.get(meta, k);
      if (m == null) {
        return;
      }
      m.idle = undefined;
      if (remote.online && current - m.fetched >= stale) {
        Reflect.set(staleKeys, k, true);
        return;
      }
    });
    let evicted = {
      contents: false
    };
    canopy.idle.forEach(k => {
      let m = Reflect.get(meta, k);
      if (m == null) {
        return;
      }
      let t = m.idle;
      if (t !== undefined) {
        if (current - t >= gc) {
          stopFetch(k);
          Reflect.deleteProperty(arrays, k);
          Reflect.deleteProperty(dicts, k);
          Reflect.deleteProperty(queries, k);
          Reflect.deleteProperty(meta, k);
          Reflect.deleteProperty(staleKeys, k);
          evicted.contents = true;
          return;
        } else {
          return;
        }
      } else {
        m.idle = current;
        return;
      }
    });
    if (!evicted.contents) {
      return;
    }
    let referenced = new Set();
    Object.keys(queries).forEach(k => {
      let ids = Reflect.get(queries, k);
      if (typeof ids !== "object") {
        return;
      }
      ids._0.forEach(id => {
        referenced.add(id);
      });
    });
    Object.keys(cache).forEach(id => {
      if (!referenced.has(id)) {
        Reflect.deleteProperty(cache, id);
        return;
      }
    });
  };
  local$1.dirty().then(rows => {
    rows.forEach(writes.send);
  });
  return {
    get: get,
    array: array,
    dict: dict,
    upsert: upsert,
    sync: sync,
    tick: tick
  };
}

export {
  Channel,
  $$Object,
  Json,
  make$2 as make,
}
/* Tilia Not a pure module */
