// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TiliaReact from "../src/TiliaReact.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Clouds(props) {
  let onClick = props.onClick;
  let tree = props.tree;
  TiliaReact.useTilia();
  let onChange = e => {
    tree.clouds.evening = e.target.value;
  };
  let isPink = TiliaReact.useComputed(() => tree.clouds.evening === "pink");
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          "Evening clouds are ",
          tree.clouds.evening
        ],
        role: "cloud"
      }),
      JsxRuntime.jsx("div", {
        children: isPink ? "Clouds are pink" : "",
        role: "flag"
      }),
      JsxRuntime.jsx("button", {
        children: "Change",
        onClick: param => onClick()
      }),
      JsxRuntime.jsx("input", {
        value: tree.clouds.evening,
        onChange: onChange
      })
    ]
  });
}

let make = Clouds;

export {
  make,
}
/* TiliaReact Not a pure module */
