// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TiliaReact from "../src/TiliaReact.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var make = TiliaReact.leaf(function (props) {
      var onClick = props.onClick;
      var tree = props.tree;
      var onChange = function (e) {
        tree.clouds.evening = e.target.value;
      };
      var isPink = TiliaReact.useComputed(function () {
            return tree.clouds.evening === "pink";
          });
      return JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsxs("div", {
                          children: [
                            "Evening clouds are ",
                            tree.clouds.evening
                          ],
                          role: "cloud"
                        }),
                    JsxRuntime.jsx("div", {
                          children: isPink ? "Clouds are pink" : "",
                          role: "flag"
                        }),
                    JsxRuntime.jsx("button", {
                          children: "Change",
                          onClick: (function (param) {
                              onClick();
                            })
                        }),
                    JsxRuntime.jsx("input", {
                          value: tree.clouds.evening,
                          onChange: onChange
                        })
                  ]
                });
    });

export {
  make ,
}
/* make Not a pure module */
