// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TiliaReact from "../src/TiliaReact.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Clouds(props) {
  var onClick = props.onClick;
  var c = TiliaReact.use(props.tree);
  var onChange = function (e) {
    c.clouds.evening = e.target.value;
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        "Evening clouds are ",
                        c.clouds.evening
                      ],
                      role: "cloud"
                    }),
                JsxRuntime.jsx("button", {
                      children: "Change",
                      onClick: (function (param) {
                          onClick();
                        })
                    }),
                JsxRuntime.jsx("input", {
                      value: c.clouds.evening,
                      onChange: onChange
                    })
              ]
            });
}

var make = Clouds;

export {
  make ,
}
/* TiliaReact Not a pure module */
