// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";

function increment(self) {
  return () => {
    self.value = self.value + 1.0;
  };
}

function decrement(self) {
  return () => {
    self.value = self.value - 1.0;
  };
}

function double(self) {
  return self.value * 2.0;
}

function make() {
  return Tilia.carve(param => {
    let derived = param.derived;
    return {
      value: 0.0,
      double: derived(double),
      increment: derived(increment),
      decrement: derived(decrement)
    };
  });
}

function observeCounter(counter, callback) {
  Tilia.observe(() => callback(counter.value));
}

export {
  increment,
  decrement,
  double,
  make,
  observeCounter,
}
/* Tilia Not a pure module */
