// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Todo from "../../src/domain/Todo.mjs";
import * as TodoList from "../../src/view/TodoList.mjs";
import * as VitestBdd from "vitest-bdd";
import * as JsxRuntime from "react/jsx-runtime";
import * as React from "@testing-library/react";
import UserEvent from "@testing-library/user-event";

VitestBdd.Given("I render the TodoList component", (param, param$1) => {
  let step = param.step;
  let host = document.createElement("div");
  document.body.appendChild(host);
  let todos = Todo.make();
  React.render(JsxRuntime.jsx(TodoList.make, {
    todos: todos
  }), {
    container: host
  });
  let screen = React.within(host);
  step("I add todo {string} with title {string}", async (id, title) => await React.act(async () => todos.add(Todo.makeTodo(id, title))));
  step("I click toggle for todo {string}", async title => {
    let user = UserEvent.setup();
    let re = new RegExp(`(Complete|Undo) ` + title);
    let btn = screen.getByRole("button", {
      name: re
    });
    return await user.click(btn);
  });
  step("I click remove for todo {string}", async title => {
    let user = UserEvent.setup();
    let btn = screen.getByRole("button", {
      name: `Remove ` + title
    });
    return await user.click(btn);
  });
  step("I should see total {string}", async expected => await React.waitFor(async () => {
    expect(screen.getByRole("status", {
      name: "Total Count"
    })).toHaveTextContent(`Total: ` + expected);
  }));
  step("I should see completed {string}", async expected => await React.waitFor(async () => {
    expect(screen.getByRole("status", {
      name: "Completed Count"
    })).toHaveTextContent(`Completed: ` + expected);
  }));
  step("I should see todo {string}", async title => await React.waitFor(async () => {
    expect(screen.getByRole("listitem", {
      name: title
    })).toBeInTheDocument();
  }));
  step("I should not see todo {string}", async title => {
    expect(screen.queryByRole("listitem", {
      name: title
    })).not.toBeInTheDocument();
  });
});

let TodoDomain;

export {
  TodoDomain,
}
/*  Not a pure module */
