// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Todo from "../../src/domain/Todo.mjs";
import * as Vitest from "vitest";
import * as VitestBdd from "vitest-bdd";

VitestBdd.Given("I have no todos", (param, param$1) => {
  let step = param.step;
  let todos = Todo.make();
  step("I add a todo with id {string} and title {string}", (id, title) => todos.add(Todo.makeTodo(id, title)));
  step("I toggle todo {string}", id => todos.toggle(id));
  step("I remove todo {string}", id => todos.remove(id));
  step("I should have {number} todos", count => Vitest.expect(todos.list.length).toBe(count));
  step("todo {string} should be completed", id => {
    let todo = todos.list.find(t => t.id === id);
    if (todo !== undefined) {
      return Vitest.expect(todo.completed).toBe(true);
    } else {
      return Vitest.expect(false).toBe(true);
    }
  });
  step("completed count should be {number}", count => Vitest.expect(todos.completedCount).toBe(count));
  step("todo {string} should not be completed", id => {
    let todo = todos.list.find(t => t.id === id);
    if (todo !== undefined) {
      return Vitest.expect(todo.completed).toBe(false);
    } else {
      return Vitest.expect(false).toBe(true);
    }
  });
});

let TodoDomain;

export {
  TodoDomain,
}
/*  Not a pure module */
