// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";

function makeTodo(id, title) {
  return {
    id: id,
    title: title,
    completed: false
  };
}

function add(self) {
  return todo => {
    self.list.push(todo);
  };
}

function toggle(self) {
  return id => {
    let t = self.list.find(t => t.id === id);
    if (t !== undefined) {
      t.completed = !t.completed;
      return;
    }
  };
}

function remove(self) {
  return id => {
    self.list = self.list.filter(todo => todo.id !== id);
  };
}

function completedCount(self) {
  return self.list.filter(todo => todo.completed).length;
}

function make() {
  return Tilia.carve(param => {
    let derived = param.derived;
    return {
      list: [],
      add: derived(add),
      toggle: derived(toggle),
      remove: derived(remove),
      completedCount: derived(completedCount)
    };
  });
}

export {
  makeTodo,
  add,
  toggle,
  remove,
  completedCount,
  make,
}
/* Tilia Not a pure module */
