// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TiliaReact from "@tilia/react/src/TiliaReact.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var make = TiliaReact.leaf(function (props) {
      var todos = props.todos;
      var todoList = todos.list;
      return JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("div", {
                          children: "Total: " + todoList.length.toString(),
                          "aria-label": "Total Count",
                          role: "status"
                        }),
                    JsxRuntime.jsx("div", {
                          children: "Completed: " + todos.completedCount.toString(),
                          "aria-label": "Completed Count",
                          role: "status"
                        }),
                    JsxRuntime.jsx("ul", {
                          children: todoList.map(function (todo) {
                                return JsxRuntime.jsxs("li", {
                                            children: [
                                              JsxRuntime.jsx("span", {
                                                    children: todo.title
                                                  }),
                                              JsxRuntime.jsx("button", {
                                                    children: todo.completed ? "Undo" : "Complete",
                                                    "aria-label": (
                                                      todo.completed ? "Undo" : "Complete"
                                                    ) + " " + todo.title,
                                                    onClick: (function (param) {
                                                        todos.toggle(todo.id);
                                                      })
                                                  }),
                                              JsxRuntime.jsx("button", {
                                                    children: "Remove",
                                                    "aria-label": "Remove " + todo.title,
                                                    onClick: (function (param) {
                                                        todos.remove(todo.id);
                                                      })
                                                  })
                                            ],
                                            "aria-label": todo.title,
                                            role: "listitem"
                                          }, todo.id);
                              }),
                          "aria-label": "Todos",
                          role: "list"
                        })
                  ]
                });
    });

export {
  make ,
}
/* make Not a pure module */
